### ISSUE TITLE
StaleElementException

### ISSUE THREAD

**Issue by morhook** [FluentLenium/FluentLenium#103]
We are getting a StaleElementException when waiting for a text on an element.

Our Scala code:

    def waitUntilIsPresentWithText(selector: String, text: String) = await().atMost(30, TimeUnit.SECONDS).until(selector).withText(text).isPresent();

Our application is re-creating the element, and that's the explanation, but from our point of view, fluentlenium should re-find the element to avoid the stacktraces.

The exception we are getting:

```
[info]       org.openqa.selenium.StaleElementReferenceException: stale element reference: element is not attached to the page document
[info]         (Session info: chrome=31.0.1650.63)
[info]         (Driver info: chromedriver=2.4.226086,platform=Mac OS X 10.9.0 x86_64) (WARNING: The server did not provide any stacktrace information)
[info]       Command duration or timeout: 10 milliseconds
[info]       For documentation on this error, please visit: http://seleniumhq.org/excepti
...

[info]       Build info: version: '2.35.0', revision: '8df0c6bedf70ff9f22c647788f9fe9c8d22210e2', time: '2013-08-17 12:46:41'
[info]       System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9', java.version: '1.6.0_65'
[info]       Session ID: b6312f8342c606f0cadf62aae0940e39
[info]       Driver info: org.openqa.selenium.remote.RemoteWebDriver
[info]       Capabilities [{platform=MAC, acceptSslCerts=true, javascriptEnabled=true, browserName=chrome, chrome={chromedriverVersion=2.4.226086}, rotatable=false, locationContextEnabled=true, version=31.0.1650.63, cssSelectorsEnabled=true, databaseEnabled=true, handlesAlerts=true, browserConnectionEnabled=false, nativeEvents=true, webStorageEnabled=true, applicationCacheEnabled=false, takesScreenshot=true}]
[info]       	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[info]       	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
[info]       	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
[info]       	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
...
```

The Selenium documentation of the bug
http://docs.seleniumhq.org/exceptions/stale_element_reference.jsp

This problem was found by @gabrieldaraio

**Comment by filipcynarski** [comment]
Could you please use the latest version of selenium and confirm is it still an issue or not?

**Comment by morhook** [comment]
I can't test this anymore as I haven't got anymore access to this application :(

**Comment by filipcynarski** [comment]
Sorry for late response, the good thing is that the FluentLenium has much more maintainers now so we'll speed up ;)

**Comment by morhook** [comment]
Sounds good! Good luck! :)
