### ISSUE TITLE
An illegal reflective access operation Warning When I Run Tests

### ISSUE THREAD

**Issue by whitejeffreyl** [FluentLenium/FluentLenium#1191]
ChromeDriver was started successfully.

[XmlClass class=com.nextgearcapital.tests.smoke.OnlineApplicationIT] - com.nextgearcapital.pageobjects.Common:waitForPageLoad - Waiting for page load
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.fluentlenium.utils.ReflectionUtils (file:/Users/jeff.white/.m2/repository/org/fluentlenium/fluentlenium-core/4.5.1/fluentlenium-core-4.5.1.jar) to field java.lang.String.value
WARNING: Please consider reporting this to the maintainers of org.fluentlenium.utils.ReflectionUtils
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by LucaLis** [comment]
I'm facing similar problem but in my case I end up with InaccessibleObjectException and test failure. I'm getting these from [chrome quick start project](https://github.com/FluentLenium/FluentLenium/tree/develop/examples/quickstart-chrome)  DuckDuckGoChromeTest:

```
java.lang.reflect.InaccessibleObjectException: Unable to make field private static final java.lang.reflect.Method jdk.proxy2.$Proxy21.m0 accessible: module jdk.proxy2 does not "opens jdk.proxy2" to unnamed module @2ef9b8bc
             at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
             at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
             at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:177)
             at java.base/java.lang.reflect.Field.setAccessible(Field.java:171)
             at org.fluentlenium.utils.ReflectionUtils.get(ReflectionUtils.java:338)
             at org.fluentlenium.core.inject.FluentElementInjectionSupportValidator.isFieldExist(FluentElementInjectionSupportValidator.java:51)
             at org.fluentlenium.core.inject.FluentElementInjectionSupportValidator.isSupported(FluentElementInjectionSupportValidator.java:38)
             at org.fluentlenium.core.inject.FluentInjector.lambda$initFluentElements$2(FluentInjector.java:192)
             at org.fluentlenium.core.inject.FluentInjector.forAllDeclaredFieldsInHierarchyOf(FluentInjector.java:242)
             at org.fluentlenium.core.inject.FluentInjector.initFluentElements(FluentInjector.java:191)
             at org.fluentlenium.core.inject.FluentInjector.inject(FluentInjector.java:105)
             at org.fluentlenium.core.inject.FluentInjector.injectComponent(FluentInjector.java:99)
             at org.fluentlenium.core.inject.FluentInjector.injectComponent(FluentInjector.java:226)
             at org.fluentlenium.core.inject.FluentInjector.lambda$initFluentElements$2(FluentInjector.java:200)
             at org.fluentlenium.core.inject.FluentInjector.forAllDeclaredFieldsInHierarchyOf(FluentInjector.java:242)
             at org.fluentlenium.core.inject.FluentInjector.initFluentElements(FluentInjector.java:191)
             at org.fluentlenium.core.inject.FluentInjector.inject(FluentInjector.java:105)
             at org.fluentlenium.core.inject.FluentInjector.lambda$initChildrenContainers$1(FluentInjector.java:170)
             at org.fluentlenium.core.inject.FluentInjector.forAllDeclaredFieldsInHierarchyOf(FluentInjector.java:242)
             at org.fluentlenium.core.inject.FluentInjector.initChildrenContainers(FluentInjector.java:161)
             at org.fluentlenium.core.inject.FluentInjector.inject(FluentInjector.java:106)
             at org.fluentlenium.core.inject.FluentInjector.inject(FluentInjector.java:92)
             at org.fluentlenium.core.FluentDriver.inject(FluentDriver.java:336)
             at org.fluentlenium.core.FluentControl.inject(FluentControl.java:512)
             at org.fluentlenium.adapter.IFluentAdapter.initFluent(IFluentAdapter.java:62)
             at org.fluentlenium.adapter.FluentTestRunnerAdapter.starting(FluentTestRunnerAdapter.java:148)
             at org.fluentlenium.adapter.junit.FluentTest.access$000(FluentTest.java:16)
             at org.fluentlenium.adapter.junit.FluentTest$1.starting(FluentTest.java:27)
             at org.fluentlenium.adapter.junit.FluentTestRule$1.evaluate(FluentTestRule.java:44)
             at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
             at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
             at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
             at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
             at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
             at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
             at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
             at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
             at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
             at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
             at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
             at org.fluentlenium.adapter.junit.FluentTest$2.evaluate(FluentTest.java:53)
             at org.junit.rules.RunRules.evaluate(RunRules.java:20)
             at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
             at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
             at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
             at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
             at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
             at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
             at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
             at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)
```
