### ISSUE TITLE
InvalidElementStateException: Element must be user-editable in order to clear it

### ISSUE THREAD

**Issue by alias1** [FluentLenium/FluentLenium#129]
Getting a `InvalidElementStateException: Element must be user-editable in order to clear it` exception with ChromeDriver and PhantomJsDriver when I try and use the `fill()` method on a HTML5 date field.

```
<input type="date" id="dob" name="dob" class="form-control input-lg required "   value="" placeholder=""/>
```

Stacktrace 
```
And fill "#dob" with "01/01/1988" remembered as "dob"                                      # WelcomerIdSteps.fillWithTextAndRemember(String,String,String)
      org.openqa.selenium.InvalidElementStateException: invalid element state: Element must be user-editable in order to clear it.
        (Session info: chrome=35.0.1916.153)
        (Driver info: chromedriver=2.10.267517,platform=Mac OS X 10.8.5 x86_64) (WARNING: The server did not provide any stacktrace information)
      Command duration or timeout: 19 milliseconds
      Build info: version: '2.42.2', revision: '6a6995d31c7c56c340d6f45a76976d43506cd6cc', time: '2014-06-03 10:52:47'
      System info: host: 'darklink.local', ip: '172.20.10.3', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.5', java.version: '1.6.0_65'
      Session ID: c027f17ada7ab3a31b1cccd55b1bb3be
      Driver info: org.openqa.selenium.chrome.ChromeDriver
      Capabilities [{platform=MAC, acceptSslCerts=true, javascriptEnabled=true, browserName=chrome, chrome={userDataDir=/var/folders/0c/ctr95jj52m9dvrj135jxfyk00000gn/T/.org.chromium.Chromium.br9ua6}, rotatable=false, locationContextEnabled=true, version=35.0.1916.153, takesHeapSnapshot=true, cssSelectorsEnabled=true, databaseEnabled=false, handlesAlerts=true, browserConnectionEnabled=false, nativeEvents=true, webStorageEnabled=true, applicationCacheEnabled=false, takesScreenshot=true}]
      	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
      	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
      	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
      	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
      	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
      	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
      	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
      	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:268)
      	at org.openqa.selenium.remote.RemoteWebElement.clear(RemoteWebElement.java:113)
      	at org.fluentlenium.core.domain.FluentWebElement.clear(FluentWebElement.java:61)
      	at org.fluentlenium.core.domain.FluentWebElement.text(FluentWebElement.java:80)
      	at org.fluentlenium.core.domain.FluentWebElement.text(FluentWebElement.java:30)
      	at org.fluentlenium.core.action.FillConstructor.with(FillConstructor.java:44)
      	at com.wlpc.welcomer.welcomertest.tests.welcomerId.WelcomerIdSteps.fillWithText(WelcomerIdSteps.java:268)
      	at com.wlpc.welcomer.welcomertest.tests.welcomerId.WelcomerIdSteps.fillWithTextAndRemember(WelcomerIdSteps.java:280)
      	at ?.And fill "#dob" with "01/01/1988" remembered as "dob"(resources/welcomerId/welcomerId.feature:46)
```

The following sound like the same sort of issue:
* https://github.com/jnicklas/capybara/issues/554
* http://stackoverflow.com/questions/15360362/clear-date-input-fails-on-chromewebdriver

Looks like [FluentWebElement.clear()](https://github.com/FluentLenium/FluentLenium/blob/master/fluentlenium-core/src/main/java/org/fluentlenium/core/domain/FluentWebElement.java#L60) needs to be updated to test for input type date as well.

There might be some other usescases that would trigger this too.. but for the one i'm hitting, this should (hopefully) fix it:

Change line 60 to:
```java
if (!isInputOfTypeFile() && !isInputOfTypeDate()) {
```

Add
```java
   /**
     * This method return true if the current FluentWebElement is an input of type date
     */
    private boolean isInputOfTypeDate() {
        return ("input".equalsIgnoreCase(this.getTagName()) &&
            "date".equalsIgnoreCase(this.getAttribute("type")));
    }
```

**Comment by carolgit** [comment]
I've got the same error when using selenium-java 2.45.0 driver FirefoxDriver when the button action is clear form element value

**Comment by NozomiIto** [comment]
Do you mean you use 'clear' method for the input element whose type is 'reset' ?
If so, you should use 'click' method to fire the reset action of the element.
'clear' method can be used for the type 'text' or 'textarea' element.

**Comment by fromi** [comment]
FYI, I am able to reproduce this error using PhantomJS 1.9.8, but no longer using version 2.0.0.

**Comment by kputh** [comment]
I think I've run into the same problem with input type _time_. More input types could be suffering from this problem.

**Comment by slawekradzyminski** [comment]
Hi Google users. There seems to be unusually high traffic to this closed issue.

We still use workaround provide above so it turned out to be a great solution.

```java
 /**
     * Clear the element
     *
     * @return fluent web element
     */
    public FluentWebElement clear() {
        if (!isInputOfTypeFile()) {
            webElement.clear();
        }
        return this;
    }
```

```java
/**
     * This method return true if the current FluentWebElement is an input of type file
     *
     * @return boolean value for is input file type
     */
    private boolean isInputOfTypeFile() {
        return "input".equalsIgnoreCase(tagName()) && "file".equalsIgnoreCase(attribute("type"));
    }
```
