### ISSUE TITLE
EventFiringWebDriver is deprecated

### ISSUE THREAD

**Issue by abendt** [FluentLenium/FluentLenium#1399]
_EventFiringWebDriver_ is marked as deprecated in Selenium 4: https://www.selenium.dev/selenium/docs/api/java/org/openqa/selenium/support/events/EventFiringWebDriver.html

* The recommended replacement _EventFiringDecorator_ is not stable yet (annotated with _@Beta_): https://www.selenium.dev/selenium/docs/api/java/org/openqa/selenium/support/events/EventFiringDecorator.html
* As the replacements is setup differently than the deprecated one this will require some changes how events are setup within FluentLenium

**Comment by diemol** [comment]
Heads up, the code has been deleted and it won't be in Selenium 4.17

**Comment by regulskimichal** [comment]
And it's gone

**Comment by mkurz** [comment]
Can't use FluentLenium 6.0.0 with latest Selenium 4.18.1:

```
[error] Caused by: java.lang.NoClassDefFoundError: org/openqa/selenium/support/events/EventFiringWebDriver
[error]     at io.fluentlenium.core.FluentDriver.<init>(FluentDriver.java:94)
[error]     at io.fluentlenium.adapter.IFluentAdapter.initFluent(IFluentAdapter.java:62)
[error]     at io.fluentlenium.adapter.IFluentAdapter.initFluent(IFluentAdapter.java:70)
```

Needs to be replaced: https://github.com/search?q=repo%3AFluentLenium%2FFluentLenium%20EventFiringWebDriver&type=code

This might help: https://www.selenium.dev/blog/2023/java-removal-of-deprecated-events-classes/

Thanks!

**Comment by mkurz** [comment]
@filipcynarski if you have time, can you give an update if or when you could work on that? Would you accept contributions so you can cut a new release soon? This is a blocker for us. Thanks!

**Comment by mkurz** [comment]
Also pinging @abendt, would appreciate a comment, thanks!

**Comment by abendt** [comment]
hi @mkurz 

To me, moving away from EventFiringWebDriver does not look like a small change, as there are some differences in how the EventFiringDecorator replacement works. Personally, I don't have the capacity to work on it; I could only offer to do reviews if you want to work on it.

**Comment by filipcynarski** [comment]
@mkurz sorry for the late response - I personally don't have the capacity too. It is a bigger refactoring. I can offer code reviews and release management but something more time-consuming is not what I can do at this stage.

**Comment by mkurz** [comment]
Thanks for the update @abendt and @filipcynarski!

@regulskimichal @diemol you commented here also, do you think you have the capacity to work on this?

**Comment by mkurz** [comment]
- I try to make this work in #2211, let's hope for the best...
