### ISSUE TITLE
org.fluentlenium.configuration.ConfigurationException: WebDriver is not available.

### ISSUE THREAD

**Issue by apsharma** [FluentLenium/FluentLenium#1593]
I use webdrivermanager to install/download the drivers for each of the browsers, alongside Fluentlenium. I am running into an issue where the tests will just not start with the error below - even though the webdriver.XXXX.driver property and path to the driver are available in the System property. Can I get some help with figuring what might be missing or causing this error ?

```
13:55:15.378 [main] DEBUG com.company.project.TestBase - Driver setup for browser: edge
13:55:15.387 [main] DEBUG com.company.project.TestBase - browser webdriver property. Key: webdriver.edge.driver, Value: /Users/asharma/.cache/selenium/msedgedriver/mac64/102.0.1245.33/msedgedriver

org.openqa.selenium.WebDriverException: Browser failed to start, test [ XXXXXXXXXXXX ] execution interrupted.
Caused by: [ WebDriver org.openqa.selenium.edge.EdgeDriver is not available.]

	at org.fluentlenium.adapter.TestRunnerCommon.getTestDriver(TestRunnerCommon.java:52)
	at org.fluentlenium.adapter.FluentTestRunnerAdapter.starting(FluentTestRunnerAdapter.java:144)
	at org.fluentlenium.adapter.testng.FluentTestNg.beforeMethod(FluentTestNg.java:72)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:65)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:381)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:319)
	at org.testng.internal.invokers.TestInvoker.runConfigMethods(TestInvoker.java:803)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:589)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.testng.TestRunner.privateRun(TestRunner.java:808)
	at org.testng.TestRunner.run(TestRunner.java:603)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
	at org.testng.SuiteRunner.run(SuiteRunner.java:326)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.runSuites(TestNG.java:1092)
	at org.testng.TestNG.run(TestNG.java:1060)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
Caused by: java.util.concurrent.ExecutionException: org.fluentlenium.configuration.ConfigurationException: WebDriver org.openqa.selenium.edge.EdgeDriver is not available.
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at org.fluentlenium.adapter.sharedwebdriver.SharedWebdriverSingletonImpl.getSharedWebDriver(SharedWebdriverSingletonImpl.java:206)
	at org.fluentlenium.adapter.sharedwebdriver.SharedWebDriverContainer.getSharedWebDriver(SharedWebDriverContainer.java:66)
	at org.fluentlenium.adapter.TestRunnerCommon.getTestDriver(TestRunnerCommon.java:46)
	... 33 more
Caused by: org.fluentlenium.configuration.ConfigurationException: WebDriver org.openqa.selenium.edge.EdgeDriver is not available.
	at org.fluentlenium.configuration.ReflectiveWebDriverFactory.newWebDriver(ReflectiveWebDriverFactory.java:83)
	at org.fluentlenium.configuration.WebDriversRegistryImpl.newWebDriver(WebDriversRegistryImpl.java:48)
	at org.fluentlenium.configuration.WebDrivers.newWebDriver(WebDrivers.java:38)
	at org.fluentlenium.adapter.sharedwebdriver.SharedWebdriverSingletonImpl.newWebDriver(SharedWebdriverSingletonImpl.java:228)
	at org.fluentlenium.adapter.sharedwebdriver.SharedWebDriverContainer.newWebDriver(SharedWebDriverContainer.java:70)
	at org.fluentlenium.adapter.IFluentAdapter.newWebDriver(IFluentAdapter.java:118)
	at org.fluentlenium.adapter.sharedwebdriver.SharedWebdriverSingletonImpl.createDriver(SharedWebdriverSingletonImpl.java:74)
	at org.fluentlenium.adapter.sharedwebdriver.SharedWebdriverSingletonImpl.createAndRegisterNewDriver(SharedWebdriverSingletonImpl.java:68)
	at org.fluentlenium.adapter.sharedwebdriver.SharedWebdriverSingletonImpl.lambda$getOrCreateDriver$0(SharedWebdriverSingletonImpl.java:63)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at org.fluentlenium.adapter.sharedwebdriver.SharedWebdriverSingletonImpl.getOrCreateDriver(SharedWebdriverSingletonImpl.java:63)
	at org.fluentlenium.adapter.sharedwebdriver.SharedWebDriverContainer.getOrCreateDriver(SharedWebDriverContainer.java:42)
	at org.fluentlenium.adapter.sharedwebdriver.SharedWebdriverSingletonImpl.lambda$createDriver$1(SharedWebdriverSingletonImpl.java:224)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
```

POM looks like this below:
```
    <properties>
        <suiteXmlFile>testng.xml</suiteXmlFile>
        <fluentlenium.version>5.0.1</fluentlenium.version>
        <selenium.version>4.1.1</selenium.version>
    </properties>
```

So, I have confirmed that this error was introduced in 5.0.1. Releases until 4.8.0 do not have this issue and the same test runs just fine on until 4.8.0.

**Comment by apsharma** [comment]
I read some previous posts where Fluentlenium decided to not include WebDriverManager as part of it but given that Selenium suggests WebDriverManager as a way to manage drivers, is it worth revisiting that decision ? https://www.selenium.dev/documentation/webdriver/getting_started/install_drivers/#1-driver-management-software

**Comment by filipcynarski** [comment]
Please check with newest Selenium and newest FluentLenium from io.fluentlenium
