### ISSUE TITLE
ConnectionException when running tests on Selenium Grid, after upgrading to 5.0.4

### ISSUE THREAD

**Issue by apsharma** [FluentLenium/FluentLenium#1707]
Folks - any pointers to what I might be missing here ? 

After upgrading Fluentlenium from 4.8.0 -> 5.0.4, the same test that was running fine against a Remote Selenium Grid starts failing with the below errors. I did explicitly add `selenium-chrome-driver` as a dependency to the pom, fwiw.

```
System info: host: 'XXXXXXXXXXX', ip: 'XXXXXXXXXXXXXXXX', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '11.5', java.version: '16.0.1'
Driver info: driver.version: unknown
	at org.fluentlenium.adapter.TestRunnerCommon.getTestDriver(TestRunnerCommon.java:52)
	at org.fluentlenium.adapter.FluentTestRunnerAdapter.starting(FluentTestRunnerAdapter.java:144)
	at org.fluentlenium.adapter.testng.FluentTestNg.beforeMethod(FluentTestNg.java:72)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:65)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:381)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:319)
	at org.testng.internal.invokers.TestInvoker.runConfigMethods(TestInvoker.java:803)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:589)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.testng.TestRunner.privateRun(TestRunner.java:808)
	at org.testng.TestRunner.run(TestRunner.java:603)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
	at org.testng.SuiteRunner.run(SuiteRunner.java:326)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.runSuites(TestNG.java:1092)
	at org.testng.TestNG.run(TestNG.java:1060)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:151)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:111)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:98)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
Caused by: java.util.concurrent.ExecutionException: org.openqa.selenium.remote.http.ConnectionFailedException: Unable to establish websocket connection to http://192.168.21.231:4444/session/8a8a742f04d70bc43061d4fe3d81972e/se/cdp
Build info: version: '4.2.2', revision: '683ccb65d6'
System info: host: 'XXXXXXXXXXX', ip: 'XXXXXXXXXXXXXXXX', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '11.5', java.version: '16.0.1'
Driver info: driver.version: unknown
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at org.fluentlenium.adapter.sharedwebdriver.SharedWebdriverSingletonImpl.getSharedWebDriver(SharedWebdriverSingletonImpl.java:206)
	at org.fluentlenium.adapter.sharedwebdriver.SharedWebDriverContainer.getSharedWebDriver(SharedWebDriverContainer.java:66)
	at org.fluentlenium.adapter.TestRunnerCommon.getTestDriver(TestRunnerCommon.java:46)
	... 39 more
Caused by: org.openqa.selenium.remote.http.ConnectionFailedException: Unable to establish websocket connection to http://192.168.21.231:4444/session/8a8a742f04d70bc43061d4fe3d81972e/se/cdp
Build info: version: '4.2.2', revision: '683ccb65d6'
System info: host: 'XXXXXXXXXXX', ip: 'XXXXXXXXXXXXXXXX', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '11.5', java.version: '16.0.1'
Driver info: driver.version: unknown
	at org.openqa.selenium.remote.http.netty.NettyWebSocket.<init>(NettyWebSocket.java:102)
	at org.openqa.selenium.remote.http.netty.NettyWebSocket.lambda$create$3(NettyWebSocket.java:128)
	at org.openqa.selenium.remote.http.netty.NettyClient.openSocket(NettyClient.java:106)
	at org.openqa.selenium.devtools.Connection.<init>(Connection.java:77)
	at org.openqa.selenium.devtools.SeleniumCdpConnection.<init>(SeleniumCdpConnection.java:34)
	at org.openqa.selenium.devtools.SeleniumCdpConnection.lambda$create$0(SeleniumCdpConnection.java:56)
	at java.base/java.util.Optional.map(Optional.java:260)
	at org.openqa.selenium.devtools.SeleniumCdpConnection.create(SeleniumCdpConnection.java:54)
	at org.openqa.selenium.devtools.SeleniumCdpConnection.create(SeleniumCdpConnection.java:47)
	at org.openqa.selenium.devtools.DevToolsProvider.getImplementation(DevToolsProvider.java:50)
	at org.openqa.selenium.devtools.DevToolsProvider.getImplementation(DevToolsProvider.java:31)
	at org.openqa.selenium.remote.Augmenter.augment(Augmenter.java:186)
	at org.fluentlenium.configuration.DefaultWebDriverFactories$RemoteWebDriverFactory.newRemoteWebDriver(DefaultWebDriverFactories.java:174)
	at org.fluentlenium.configuration.DefaultWebDriverFactories$RemoteWebDriverFactory.newInstance(DefaultWebDriverFactories.java:154)
	at org.fluentlenium.configuration.ReflectiveWebDriverFactory.newWebDriver(ReflectiveWebDriverFactory.java:97)
	at org.fluentlenium.configuration.WebDriversRegistryImpl.newWebDriver(WebDriversRegistryImpl.java:48)
	at org.fluentlenium.configuration.WebDrivers.newWebDriver(WebDrivers.java:38)
	at org.fluentlenium.adapter.sharedwebdriver.SharedWebdriverSingletonImpl.newWebDriver(SharedWebdriverSingletonImpl.java:228)
	at org.fluentlenium.adapter.sharedwebdriver.SharedWebDriverContainer.newWebDriver(SharedWebDriverContainer.java:70)
	at org.fluentlenium.adapter.IFluentAdapter.newWebDriver(IFluentAdapter.java:118)
	at org.fluentlenium.adapter.sharedwebdriver.SharedWebdriverSingletonImpl.createDriver(SharedWebdriverSingletonImpl.java:74)
	at org.fluentlenium.adapter.sharedwebdriver.SharedWebdriverSingletonImpl.createAndRegisterNewDriver(SharedWebdriverSingletonImpl.java:68)
	at org.fluentlenium.adapter.sharedwebdriver.SharedWebdriverSingletonImpl.lambda$getOrCreateDriver$0(SharedWebdriverSingletonImpl.java:63)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at org.fluentlenium.adapter.sharedwebdriver.SharedWebdriverSingletonImpl.getOrCreateDriver(SharedWebdriverSingletonImpl.java:63)
	at org.fluentlenium.adapter.sharedwebdriver.SharedWebDriverContainer.getOrCreateDriver(SharedWebDriverContainer.java:42)
	at org.fluentlenium.adapter.sharedwebdriver.SharedWebdriverSingletonImpl.lambda$createDriver$1(SharedWebdriverSingletonImpl.java:224)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
```

POM details/changes

```
<fluentlenium.version>5.0.4</fluentlenium.version>
<selenium.version>4.2.2</selenium.version>

<dependency>
      <groupId>org.seleniumhq.selenium</groupId>
      <artifactId>selenium-chrome-driver</artifactId>
      <version>${selenium.version}</version>
</dependency>
```

**Comment by ttwhy** [comment]
had pretty much the same. defining a capabilities property with firefox fixed this issue. the chrome capabilie is still broken in my case. 

so workaround was:
`capabilities=firefox`
in the fluentlenium.properties file

**Comment by ttwhy** [comment]
To share more info about the failing capability:
`org.openqa.selenium.WebDriverException: Browser failed to start, test [ startProgramm ] execution interrupted.
Caused by: [ Could not start a new session. Response code 500. Message: Unable to create session from {
  "desiredCapabilities": {
    "browserName": "chrome",
    "server:CONFIG_UUID": "f148b7e4-3e99-4826-9c6c-85a18612bbcc",
    "browserVersion": ""
  },
  "capabilities": {
    "firstMatch": [
      {
        "browserName": "chrome",
        "browserVersion": "",
        "server:CONFIG_UUID": "f148b7e4-3e99-4826-9c6c-85a18612bbcc"
      }
    ]
  }
}`

The same capability works with 4.8 flawless.

**Comment by filipcynarski** [comment]
I'm curious about what happens when we upgrade Selenium to the most recent version, FluentLenium was relying on DesiredCapabilities which were deprecated in the newest Selenium & Grid releases, it makes this upgrade more crucial. It is not an easy task and may take some time. What I can promise it will be P1 on my todo list and try to deliver this upgrade for you to check if is it fixing your problem in 1-2 weeks.

**Comment by filipcynarski** [comment]
We are up to date and Selenium is also upgraded in FL, could you please confirm it does the job for you @apsharma
