### ISSUE TITLE
Add Java17 support

### ISSUE THREAD

**Issue by filipcynarski** [FluentLenium/FluentLenium#1758]
Current blocker is some issue with Reflection utils, can be tested by `FluentInjectorComponentTest`

It throws:

```
ava.lang.reflect.InaccessibleObjectException: Unable to make field private static final java.lang.reflect.Method jdk.proxy2.$Proxy47.m0 accessible: module jdk.proxy2 does not "opens jdk.proxy2" to unnamed module @3f8f9dd6

	at java.base/java.lang.reflect.AccessibleObject.throwInaccessibleObjectException(AccessibleObject.java:387)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:363)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:311)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:180)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:174)
	at org.fluentlenium.utils.ReflectionUtils.get(ReflectionUtils.java:338)
	at org.fluentlenium.core.inject.FluentElementInjectionSupportValidator.isFieldExist(FluentElementInjectionSupportValidator.java:51)
	at org.fluentlenium.core.inject.FluentElementInjectionSupportValidator.isSupported(FluentElementInjectionSupportValidator.java:38)
	at org.fluentlenium.core.inject.FluentInjector.lambda$initFluentElements$2(FluentInjector.java:203)
	at org.fluentlenium.core.inject.FluentInjector.forAllDeclaredFieldsInHierarchyOf(FluentInjector.java:253)
	at org.fluentlenium.core.inject.FluentInjector.initFluentElements(FluentInjector.java:202)
	at org.fluentlenium.core.inject.FluentInjector.inject(FluentInjector.java:116)
	at org.fluentlenium.core.inject.FluentInjector.injectComponent(FluentInjector.java:110)
```

**Comment by filipcynarski** [comment]
@abendt are you able to check this out?

**Comment by abendt** [comment]
> @abendt are you able to check this out?

will have a look at the issue

**Comment by abendt** [comment]
@filipcynarski i found a solution. check the linked PR

**Comment by filipcynarski** [comment]
Well done @abendt ! merged
