### ISSUE TITLE
java.lang.UnsupportedOperationException: getDomAttribute

### ISSUE THREAD

**Issue by zerikv** [FluentLenium/FluentLenium#2172]
With the version 6.0.0, when the element `org.openqa.selenium.support.ui.Select` is instantiate, the following error is thrown : 
```
java.lang.UnsupportedOperationException: getDomAttribute

	at org.openqa.selenium.WebElement.getDomAttribute(WebElement.java:131)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.fluentlenium.core.proxy.AbstractLocatorAndInvocationHandler.invoke(AbstractLocatorAndInvocationHandler.java:118)
	at io.fluentlenium.core.proxy.AbstractLocatorAndInvocationHandler.invokeWithRetry(AbstractLocatorAndInvocationHandler.java:104)
	at io.fluentlenium.core.proxy.AbstractLocatorAndInvocationHandler.invoke(AbstractLocatorAndInvocationHandler.java:52)
	at io.fluentlenium.core.proxy.ComponentHandler.invoke(ComponentHandler.java:97)
	at jdk.proxy2/jdk.proxy2.$Proxy101.getDomAttribute(Unknown Source)
	at org.openqa.selenium.support.ui.Select.<init>(Select.java:54)
```

As I understand, the implementation of the method `getDomAttribute` is missing in the class `io.fluentlenium.core.hook.BaseHook` . 

You can workaround, by using a Hook which implements this method :
```java
	@Override
	public String getDomAttribute(final String name) {
		return this.getElement().getDomAttribute(name);
	}
```

**Comment by mkurz** [comment]
@zerikv How about a pull request to get this fixed?

**Comment by zerikv** [comment]
The Pull Request is here : https://github.com/FluentLenium/FluentLenium/pull/2217
