### ISSUE TITLE
TestNG BeforeClass annotation don't work with Fluent

### ISSUE THREAD

**Issue by flyAwayGG** [FluentLenium/FluentLenium#269]
Hi. I really love your framework, but i have one big problem with TestNG. I can't use BeforeClass annotation because driver cannot i get NPE. Below is test code that repeat my problem.
Tests inheritance: CheckMethods  -> TestBase -> FluentTestNg
```
public class CheckMethods extends TestBase {
    private LoginPage loginPage;

    @BeforeClass
    public void beforeClassInitialization() {
        loginPage = createPage(LoginPage.class);
        loginPage.goToActiveNode();
    }
    @Test
    private void test(){}
}
``` 
```
public abstract class TestBase extends FluentTestNg{
    private WebDriver webDriver;

    @Override
    public WebDriver getDefaultDriver(){
        return webDriver;
    }
    @BeforeSuite
    private WebDriver initializeWebDriver() throws IOException {
         webDriver = new FirefoxDriver();
    }
}
```
Pages inheritance: LoginPage(just empty) -> Page -> FluentPage 
```
public abstract class Page extends FluentPage {
    public void goToActiveNode() {
        System.out.println("https://google.com");
        goTo("https://google.com");
    }
```

Output is:
```
https://google.com

java.lang.NullPointerException
	at org.fluentlenium.core.Fluent.goTo(Fluent.java:325)
	at com.raidix.testing.pages.Page.goToActiveNode(Page.java:52) // goTo(activeUrl);  
	at com.raidix.testing.tests.CheckMethods.beforeClassInitialization(CheckMethods.java:34)
```
In Fluent.java exception in goTo method declaration on line "this.getDriver().get(url);".
What i do for fix this:

1. Use @Page annotation. 
BeforeClass start before annotation body intialize and we get NPE in first call of pageobject method.
2. In tests `private LoginPage = createPage(LoginPage.class);` 
This throw exception like in all test code above. But when we initialize URL in variable:
```
public abstract class Page extends FluentPage {
private String url = getUrl();
    public void goToActiveNode() {
        System.out.println(url);
        goTo(url);
    }
```
We get next exception:
```
null
 java.lang.IllegalArgumentException: Url is mandatory

	at org.fluentlenium.core.Fluent.goTo(Fluent.java:317) //at throwing new exception
```
3..When move all from @BeforeClass method to @BeforeMethod, all works correctly.

 Is this my problem and how can i avoid this?

**Comment by Toilal** [comment]
By default, FluentLenium creates a new driver for each method by calling ```getDefaultDriver()``` function.

If you want a single driver for the whole class execution, you have to put ```@SharedDriver(type = SharedDriver.SharedType.PER_CLASS)``` on the test class.

I think i'll rename this function in the next release with ```createDriver()``` so it's more explicit. Implementation should always return a new fresh instance. Hope this will help you.

**Comment by flyAwayGG** [comment]
No, i simplify my test example:
```
public class Test extends FluentTestNg {

    private LoginPage loginPage;

    @BeforeClass
    private void beforeClass(){
        loginPage = createPage(LoginPage.class);
        loginPage.goTo("https://google.com");
    }
    @Test
    private void doNothing(){}
}
```
LoginPage have parent FluentPage
and i get exception in Fluent class in line where we try to get driver:  this.getDriver().get(url); :
```
java.lang.NullPointerException
	at org.fluentlenium.core.Fluent.goTo(Fluent.java:325)
	at com.raidix.testing.tests.single.Qqq.beforeClass(Qqq.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:178)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:74)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:121)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```
Without this TestNg feature i can not write preconditions for tests, and that's bad

**Comment by Toilal** [comment]
It doesn't make sense to write such test class.

You can't access WebDriver in @BeforeClass with default @SharedDriver value (PER_METHOD), because a new WebDriver is created before each method, and at the time @BeforeClass method is called, WebDriver is not initialized.

So you have 2 possible options to fix your issue :

1) Put ```@SharedDriver(type = SharedDriver.SharedType.PER_CLASS)``` on your test class. (doing so will create the WebDriver instance for the whole class, and will be shared for each method)

2) Replace @BeforeClass with @BeforeMethod. (A new WebDriver instance will be created for each method, and this is the default FluentLenium Behavior)

**Comment by flyAwayGG** [comment]
First option is not working, i get same exception. Now i use second option, but i need BeforeClass annotation for creating test class preconditions.

**Comment by Toilal** [comment]
Ok, so i'll try to edit sources for option 1 to work. But for now you should stick to @BeforeMethod annotation.

**Comment by flyAwayGG** [comment]
Thank you!

**Comment by Toilal** [comment]
After more investigation, I can't implement changes for option 1.

Trying to port this example on JUnit doesn't work too : with JUnit, @BeforeClass method must be static, so access to createPage is not even possible. It also doesn't load the page when using @Page annotation. 

As FluentTestRunnerAdapter are currently written, @BeforeClass can't be used to work on the WebDriver.

**Comment by johncam1** [comment]
fg
