### ISSUE TITLE
Test example fails

### ISSUE THREAD

**Issue by TestBoy69** [FluentLenium/FluentLenium#483]
I am able to compile the FluentLenium sources with external maven. All tests passes.
However, when trying to run provided test examples I get error:

java.lang.Error: Unresolved compilation problem: 
	The method getOrCreateDriver(new Supplier<WebDriver>(){}, Class<capture#6-of ?>, String, ConfigurationProperties.DriverLifecycle) is undefined for the type SharedWebDriverContainer

	at org.fluentlenium.adapter.FluentTestRunnerAdapter.starting(FluentTestRunnerAdapter.java:87)
	at org.fluentlenium.adapter.junit.FluentTest.access$0(FluentTest.java:1)
	at org.fluentlenium.adapter.junit.FluentTest$1.starting(FluentTest.java:25)
	at org.fluentlenium.adapter.junit.FluentTestRule$1.evaluate(FluentTestRule.java:43)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.fluentlenium.adapter.junit.FluentTest$2$1.evaluate(FluentTest.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

java.lang.Error: Unresolved compilation problems: 
	The method getDriver(Class<capture#14-of ?>, String, ConfigurationProperties.DriverLifecycle) is undefined for the type SharedWebDriverContainer
	The method quit(SharedWebDriver) is undefined for the type SharedWebDriverContainer
	The method getDriver(Class<capture#18-of ?>, String, ConfigurationProperties.DriverLifecycle) is undefined for the type SharedWebDriverContainer

	at org.fluentlenium.adapter.FluentTestRunnerAdapter.finished(FluentTestRunnerAdapter.java:135)
	at org.fluentlenium.adapter.junit.FluentTest.access$1(FluentTest.java:1)
	at org.fluentlenium.adapter.junit.FluentTest$1.finished(FluentTest.java:31)
	at org.fluentlenium.adapter.junit.FluentTestRule$1.evaluate(FluentTestRule.java:62)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.fluentlenium.adapter.junit.FluentTest$2$1.evaluate(FluentTest.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

Please help.

**Comment by filipcynarski** [comment]
@TestBoy69 are opening the examples as separate project or withing FL sources as a module?

**Comment by TestBoy69** [comment]
As a separate project. I created it by copying sources and pom to new project.

**Comment by Toilal** [comment]
Do you run JDK 8 ?

**Comment by filipcynarski** [comment]
No response from @TestBoy69 from a long time. I assume issue resolved.
