### ISSUE TITLE
IllegalArgumentException: object is not an instance of declaring class

### ISSUE THREAD

**Issue by robxu9** [FluentLenium/FluentLenium#491]
Trying to use either `keyboard()` or `mouse()` on an element results in the following stacktrace:

```
java.lang.IllegalArgumentException: object is not an instance of declaring class

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.fluentlenium.core.proxy.AbstractLocatorHandler.invoke(AbstractLocatorHandler.java:294)
	at org.fluentlenium.core.proxy.AbstractLocatorHandler.invokeWithRetry(AbstractLocatorHandler.java:280)
	at org.fluentlenium.core.proxy.AbstractLocatorHandler.invoke(AbstractLocatorHandler.java:272)
	at org.fluentlenium.core.proxy.ComponentHandler.invoke(ComponentHandler.java:98)
	at com.sun.proxy.$Proxy38.getCoordinates(Unknown Source)
	at org.openqa.selenium.interactions.internal.MouseAction.getActionLocation(MouseAction.java:51)
	at org.openqa.selenium.interactions.internal.MouseAction.moveToLocation(MouseAction.java:58)
	at org.openqa.selenium.interactions.DoubleClickAction.perform(DoubleClickAction.java:39)
	at org.openqa.selenium.interactions.CompositeAction.perform(CompositeAction.java:50)
	at org.openqa.selenium.interactions.Actions.perform(Actions.java:373)
	at org.fluentlenium.core.action.MouseElementActions.doubleClick(MouseElementActions.java:109)
	at org.fluentlenium.core.domain.FluentWebElement.doubleClick(FluentWebElement.java:120)
```

...followed by wherever I called .mouse() or .keyboard() (or anything that uses it, like .doubleClick()).

It's causing me to be unable to double-click items.

I'm using Fluentlenium 3.1.1 with Chrome 57 and Selenium 3.0.1.

**Comment by filipcynarski** [comment]
@robxu9 let me test it on the newest versions of Selenium and FluentLenium and I'll check is it still a case.

**Comment by filipcynarski** [comment]
I've retested it and seems to working fine @robxu9

**Comment by dominik1776** [comment]
Looks like there is still an issue indeed. Getting the same exception for env:
* Google Chrome | 67.0.3396.62 (Official Build) (64-bit)
* Selenium version 3.12.0
* Fluentlenium version 3.5.2 
Is there any workaround for this?

**Comment by ouchxp** [comment]
Having the same issue here. My workaround is to call `noHook()` on the element. I assume the proxy object somehow is not properly generated.

**Comment by filipcynarski** [comment]
@ouchxp @dominik1776 would you be able to provide the code which causing the issue?

**Comment by filipcynarski** [comment]
I've got the description from @TomaszSzyborski 

it is not important is the element defined by `FindBy` or `el` it fails w/ following exception

```
Throws exception:
elem.mouse().moveToElement();
java.lang.IllegalArgumentException: object is not an instance of declaring class                    

Passes:
elem.noHook().mouse().moveToElement();
```

**Comment by filipcynarski** [comment]
Very interesting is a fact the test is passing for this part of code:

`ActionOnSelectorAdvancedUserIntegrationTest#checkMouseOverAction`

**Comment by filipcynarski** [comment]
Ok, looks like `@Wait` annotation is causing the issue

this code won't work:

```java
package org.fluentlenium.examples.quickstart;

import org.fluentlenium.adapter.junit.FluentTest;
import org.fluentlenium.core.hook.wait.Wait;
import org.junit.Test;

import static org.assertj.core.api.Assertions.assertThat;

@Wait
public class DuckDuckGoTest extends FluentTest {
    @Test
    public void titleOfDuckDuckGoShouldContainSearchQueryName() {
        goTo("https://boardgamegeek.com/");
        el(".submenutabs .fl").mouse().moveToElement();
    }
}
```

this is working well

```java
package org.fluentlenium.examples.quickstart;

import org.fluentlenium.adapter.junit.FluentTest;
import org.fluentlenium.core.hook.wait.Wait;
import org.junit.Test;

import static org.assertj.core.api.Assertions.assertThat;

public class DuckDuckGoTest extends FluentTest {
    @Test
    public void titleOfDuckDuckGoShouldContainSearchQueryName() {
        goTo("https://boardgamegeek.com/");
        el(".submenutabs .fl").mouse().moveToElement();
    }
}
```

**Comment by koryl** [comment]
This issue is related to #595.

**Comment by koryl** [comment]
This issue is related to #595.

**Comment by filipcynarski** [comment]
Issue resolved, code merged to develop
