### ISSUE TITLE
Chrome driver failure with 3.2.0

### ISSUE THREAD

**Issue by Toilal** [FluentLenium/FluentLenium#499]
I try to upgrade to 3.2.0, but it fails with Chrome driver.

```
org.fluentlenium.configuration.ConfigurationException: Can't create new WebDriver instance
    at org.fluentlenium.configuration.ReflectiveWebDriverFactory.newWebDriver(ReflectiveWebDriverFactory.java:104)
    at org.fluentlenium.configuration.WebDriversRegistryImpl.newWebDriver(WebDriversRegistryImpl.java:48)
    at org.fluentlenium.configuration.WebDrivers.newWebDriver(WebDrivers.java:17)
    at org.fluentlenium.adapter.FluentAdapter.newWebDriver(FluentAdapter.java:139)
    at org.fluentlenium.adapter.FluentStandalone.init(FluentStandalone.java:13)
    at org.fluentlenium.adapter.FluentStandaloneRunnable.run(FluentStandaloneRunnable.java:12)
    at com.pragmasphere.oika.automator.commands.identifiants.IdentifiantsCommand.accesFromRegroupement(IdentifiantsCommand.java:102)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:216)
    at org.springframework.shell.core.SimpleExecutionStrategy.invoke(SimpleExecutionStrategy.java:68)
    at org.springframework.shell.core.SimpleExecutionStrategy.execute(SimpleExecutionStrategy.java:59)
    at org.springframework.shell.core.AbstractShell.executeCommand(AbstractShell.java:134)
    at org.springframework.shell.core.JLineShell.promptLoop(JLineShell.java:533)
    at org.springframework.shell.core.JLineShell.run(JLineShell.java:179)
    at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at org.fluentlenium.utils.ReflectionUtils.newInstance(ReflectionUtils.java:266)
    at org.fluentlenium.configuration.ReflectiveWebDriverFactory.newInstance(ReflectiveWebDriverFactory.java:127)
    at org.fluentlenium.configuration.ReflectiveWebDriverFactory.newWebDriver(ReflectiveWebDriverFactory.java:102)
    ... 17 more
Caused by: java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkState(ZLjava/lang/String;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)V
    at org.openqa.selenium.remote.service.DriverService.findExecutable(DriverService.java:111)
    at org.openqa.selenium.chrome.ChromeDriverService.access$000(ChromeDriverService.java:32)
    at org.openqa.selenium.chrome.ChromeDriverService$Builder.findDefaultExecutable(ChromeDriverService.java:137)
    at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:302)
    at org.openqa.selenium.chrome.ChromeDriverService.createDefaultService(ChromeDriverService.java:88)
    at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:120)
```

**Comment by filipcynarski** [comment]
@toilal could you Please check the version of chrome driver which you are using it word great w/ chrome for me. Please provide the chrome driver version here

**Comment by Toilal** [comment]
I just upgraded to 3.3.1 but it doesn't fix the issue. Maybe there's something wrong in my dependency tree though.

**Comment by filipcynarski** [comment]
It must be an issue w/ your environment it works well on brand new project which I've already created and the same in case of legacy project after upgrade. I've tested custom configuration class and @FluentConfiguration(baseUrl = "http://google.com", webDriver = "chrome") no issues identified. You may facing issue related to ChromeBrowser upgrade, let's check your chrome version, webdriver version and try to run using pure selenium, if the issue is still on your side please reopen the issue and add example project so I'll try to investigated again.
