### ISSUE TITLE
Generic lists issue

### ISSUE THREAD

**Issue by filipcynarski** [FluentLenium/FluentLenium#501]
When I'm creating more sophisticated structure of my project I'm facing issues related to reflection and generic types.

For code like this:

```
public class AbstractFopsFilter<T extends AbstractFrontOfPack> extends WebPageComponent {
    private List<T> fops;

    @Override
    public void verifyIfIsLoaded() {
    }

```

I'm getting error for pages which are extending AbstractFopsFilter

```
java.lang.ClassCastException: sun.reflect.generics.reflectiveObjects.TypeVariableImpl cannot be cast to java.lang.Class

	at org.fluentlenium.utils.ReflectionUtils.getFirstGenericType(ReflectionUtils.java:456)
	at org.fluentlenium.core.inject.FluentInjector.isListOfFluentWebElement(FluentInjector.java:381)
	at org.fluentlenium.core.inject.FluentInjector.isSupported(FluentInjector.java:348)
	at org.fluentlenium.core.inject.FluentInjector.initFluentElements(FluentInjector.java:206)
	at org.fluentlenium.core.inject.FluentInjector.inject(FluentInjector.java:113)
	at org.fluentlenium.core.inject.FluentInjector.inject(FluentInjector.java:97)
	at org.fluentlenium.core.inject.FluentInjector.newInstance(FluentInjector.java:91)
	at org.fluentlenium.core.FluentDriver.newInstance(FluentDriver.java:65)
	at org.fluentlenium.core.inject.ContainerFluentControl.newInstance(ContainerFluentControl.java:20)
	at org.fluentlenium.adapter.FluentAdapter.newInstance(FluentAdapter.java:51)
	at org.fluentlenium.core.inject.ContainerFluentControl.newInstance(ContainerFluentControl.java:20)
	at org.fluentlenium.core.DefaultFluentContainer.newInstance(DefaultFluentContainer.java:28)
```

**Comment by filipcynarski** [comment]
This is why @NoInject was introduced, add @NoInject to `private List<T> fops;` field
