### ISSUE TITLE
Support for SerenityRunner?

### ISSUE THREAD

**Issue by nmarra** [FluentLenium/FluentLenium#504]
I was trying to get your sample to run with the @RunWith(SerenityRunner.class) tag, in order to track the results in a Serenity report; however I get the following exception when trying to run with maven clean install:

```
java.lang.ExceptionInInitializerError
Caused by: org.fluentlenium.configuration.ConfigurationException: class org.fluentlenium.configuration.DefaultWebDriverFactories$HtmlUnitWebDriverFactory can't be instantiated.
Caused by: java.lang.reflect.InvocationTargetException
Caused by: java.lang.NoClassDefFoundError: org/openqa/selenium/remote/SessionNotFoundException
Caused by: java.lang.ClassNotFoundException: org.openqa.selenium.remote.SessionNotFoundException
```

Using the Intellij JUnit runner gives a more detailed error:
```

java.lang.ExceptionInInitializerError
	at org.fluentlenium.adapter.FluentAdapter.newWebDriver(FluentAdapter.java:139)
	at org.fluentlenium.adapter.FluentTestRunnerAdapter$1.get(FluentTestRunnerAdapter.java:90)
	at org.fluentlenium.adapter.FluentTestRunnerAdapter$1.get(FluentTestRunnerAdapter.java:87)
	at org.fluentlenium.adapter.SharedWebDriverContainer$Impl.createDriver(SharedWebDriverContainer.java:81)
	at org.fluentlenium.adapter.SharedWebDriverContainer$Impl.getOrCreateDriver(SharedWebDriverContainer.java:72)
	at org.fluentlenium.adapter.SharedWebDriverContainer.getOrCreateDriver(SharedWebDriverContainer.java:26)
	at org.fluentlenium.adapter.FluentTestRunnerAdapter.starting(FluentTestRunnerAdapter.java:87)
	at org.fluentlenium.adapter.junit.FluentTest.access$000(FluentTest.java:15)
	at org.fluentlenium.adapter.junit.FluentTest$1.starting(FluentTest.java:25)
	at org.fluentlenium.adapter.junit.FluentTestRule$1.evaluate(FluentTestRule.java:43)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at net.serenitybdd.junit.runners.SerenityRunner.performRunChild(SerenityRunner.java:460)
	at net.serenitybdd.junit.runners.SerenityRunner.runChild(SerenityRunner.java:433)
	at net.serenitybdd.junit.runners.SerenityRunner.runChild(SerenityRunner.java:53)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.fluentlenium.adapter.junit.FluentTest$2$1.evaluate(FluentTest.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at net.serenitybdd.junit.runners.SerenityRunner.run(SerenityRunner.java:248)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: org.fluentlenium.configuration.ConfigurationException: class org.fluentlenium.configuration.DefaultWebDriverFactories$HtmlUnitWebDriverFactory can't be instantiated.
	at org.fluentlenium.configuration.AbstractFactoryRegistryImpl.<init>(AbstractFactoryRegistryImpl.java:57)
	at org.fluentlenium.configuration.WebDriversRegistryImpl.<init>(WebDriversRegistryImpl.java:16)
	at org.fluentlenium.configuration.WebDrivers.<init>(WebDrivers.java:17)
	at org.fluentlenium.configuration.WebDrivers.<clinit>(WebDrivers.java:15)
	... 30 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at org.fluentlenium.configuration.AbstractFactoryRegistryImpl.<init>(AbstractFactoryRegistryImpl.java:53)
	... 33 more
Caused by: java.lang.NoClassDefFoundError: org/openqa/selenium/remote/SessionNotFoundException
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:259)
	at org.fluentlenium.configuration.ReflectiveWebDriverFactory.<init>(ReflectiveWebDriverFactory.java:35)
	at org.fluentlenium.configuration.DefaultWebDriverFactories$HtmlUnitWebDriverFactory.<init>(DefaultWebDriverFactories.java:113)
	... 38 more
Caused by: java.lang.ClassNotFoundException: org.openqa.selenium.remote.SessionNotFoundException
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 42 more

```

I was wondering if there is an accepted or known way to integrate FluentLenium with Serenity reporting.  The extension library provided is great and I'd love to integrate it into our current testing workflow.

**Comment by nmarra** [comment]
Thank you for adding this to the 3.3 milestone list.  I found that the issue stems from the serenity-core artifact, even just including it in the pom will cause the exception mentioned above to be thrown. 
`
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-core</artifactId>
            <version>1.4.0</version>
        </dependency>
`

**Comment by filipcynarski** [comment]
Thank you @nmarra for adding more information to the task, we will try to address it in next release.

**Comment by nmarra** [comment]
No problem @filipcynarski.  Feel free to contact me if you need any additional information.  I was able to solve the issue with the tests not reporting failures by adding `<testFailureIgnore>true</testFailureIgnore>` to my maven-surefire-plugin configuration.  
Also I worked around the selenium-core dependency conflict by adding it as dependency of the serenity-maven-plugin in the build-->plugins portion of the maven pom.  I zipped up my pom and attached it which will hopefully help reproduce the issue.  Thank you

[pom.zip](https://github.com/FluentLenium/FluentLenium/files/1064142/pom.zip)

**Comment by pavi200863** [comment]
Hi @nmarra  , I am also facing same issue .Any temporary solution to resolve this issue ?

**Comment by filipcynarski** [comment]
@pavi200863 I can consider to add this changes to current release, please wait for next release.

**Comment by nmarra** [comment]
@pavi200863 We stopped using FluentLenium due to the lack of this support.

**Comment by filipcynarski** [comment]
Shame on me :( we will add this support soon guys sorry I’m keen to merge
pull requests now I’m only one person with limited time ;) as eveyobody on
the earth :)

W dniu pon., 20.11.2017 o 15:56 nmarra <notifications@github.com>
napisał(a):
