### ISSUE TITLE
Unable to run TestNG with threading

### ISSUE THREAD

**Issue by tienlong826** [FluentLenium/FluentLenium#508]
So the simple test launches two browser, but then once they launched, the script fails.

This is my script:
`public class GoogleSimpleTest extends FluentTestNg {

    // Defines the Driver
    private static ThreadLocal<WebDriver> WebDriverTL = new ThreadLocal<WebDriver>();

    public void setWebdriver(WebDriver driver){
        WebDriverTL.set(driver);
    }

    @Override
    public WebDriver newWebDriver() {
        return WebDriverTL.get ();
    }

    @BeforeMethod
    public void launchbrowser(){
        WebDriver driver = new ChromeDriver();
        setWebdriver(driver);
    }

    @Test(invocationCount = 2, threadPoolSize = 2)
    public void GoogleTest(){
        goTo("http://google.com");
        System.out.println(getCookies());
    }
}`

This is the error I get:
`java.lang.NullPointerException
	at org.fluentlenium.adapter.FluentAdapter.goTo(FluentAdapter.java:51)
	at LoadTestLW.GoogleTest(LoadTestLW.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

java.lang.NullPointerException
	at org.fluentlenium.adapter.FluentAdapter.goTo(FluentAdapter.java:51)
	at LoadTestLW.GoogleTest(LoadTestLW.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)'

**Comment by filipcynarski** [comment]
@tienlong826 you are using FluentLenium in wrong way. Your tests should extend FluentTest, and driver should be configured in properties or override newWebDriver method which is inherited from FluentTest, please make sure are you using fluentlenium-testng library and let me know if you still facing issues.

```
    @Override
    public WebDriver newWebDriver() {
        try {
            return new Augmenter().augment(new RemoteWebDriver(new URL(System.getenv("browserstackurl")), chrome()));
        } catch (MalformedURLException e) {
            return null;
        }
    }
```

This one is evil:

```
// Defines the Driver
private static ThreadLocal<WebDriver> WebDriverTL = new ThreadLocal<WebDriver>();

public void setWebdriver(WebDriver driver){
    WebDriverTL.set(driver);
}

@Override
public WebDriver newWebDriver() {
    return WebDriverTL.get ();
}

@BeforeMethod
public void launchbrowser(){
    WebDriver driver = new ChromeDriver();
    setWebdriver(driver);
}
```

Rid this out for sure ;)

**Comment by tienlong826** [comment]
@filipcynarski 
Doing so with FluentTest alone, how would I invoke it to run 1 method multiple time in threads? (per say I need to run 1 method with 5 chrome browser all at once?)

That is what I am trying to achieve but I couldn't with FluentLenium :(

**Comment by tienlong826** [comment]
I manage to get it to work by using WebDrive, but I couldn't get it to work with the Standalone.
When I tried to use the Standalone, It would open up Chrome, then Firefox, then Chrome.

This is my code to get it to work with WebDriver.
public class Corkboard extends IntegrationFluentTestNg {

        @Test(invocationCount = 2, threadPoolSize = 2)
        public void GoogleTest() throws Exception {
            DesiredCapabilities caps = new DesiredCapabilities();
            WebDriver driver = new ChromeDriver(caps);
            driver.get(DEFAULT_URL);
            System.out.println(driver.manage().getCookies());
            driver.quit();
        }
}

public class IntegrationFluentTestNg extends FluentTestNg {
    private WebDriver driver;
    public static final String DEFAULT_URL;

    static {
        DEFAULT_URL = "http://google.com";
    }

    @Override
    public String getWebDriver() {
        return "chrome";
    }


How would I get to work with the StandAlone mode and not get the behaviors I got above?

**Comment by filipcynarski** [comment]
@tienlong826 it is working for me:

```java
public class ExampleTest extends FluentTestNg {
    private final static String DEFAULT_URL = "http://google.com";

    public WebDriver newWebDriver() {
        DesiredCapabilities caps = new DesiredCapabilities();
        WebDriver driver = new ChromeDriver(caps);
        return driver;
    }


    @Test(invocationCount = 2, threadPoolSize = 2)
    public void GoogleTest() throws Exception {
        DesiredCapabilities caps = new DesiredCapabilities();
        WebDriver driver = new ChromeDriver(caps);
        driver.get(DEFAULT_URL);
        System.out.println(driver.manage().getCookies());
        driver.quit();
    }
}
```

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>fluentlenium-testng-multithreading</groupId>
    <artifactId>com.fluentlenium.testng.multithreading</artifactId>
    <version>1.0-SNAPSHOT</version>

    <dependencies>
        <dependency>
            <groupId>org.fluentlenium</groupId>
            <artifactId>fluentlenium-testng</artifactId>
            <version>3.2.0</version>
        </dependency>
        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>6.9.10</version>
        </dependency>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-chrome-driver</artifactId>
            <version>3.3.1</version>
        </dependency>
    </dependencies>

</project>
```

**Comment by filipcynarski** [comment]
You mistake is you are trying to create webdriver outside FluentLenium, the library doesn't knew about that and it led you to errors and it went out of your control.

**Comment by tienlong826** [comment]
Thank you so much for taking your time to help me. I copy the code you pasted above into my project along with the POM. When I ran it, only one browser open and the 2nd test failed. Could you look at the stack trace and help me understand why it's failing?


```
Starting ChromeDriver 2.30.477690 (c53f4ad87510ee97b5c3425a14c0e79780cdf262) on port 6415
Only local connections are allowed.
Jun 17, 2017 3:21:39 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS

org.openqa.selenium.NoSuchSessionException: no such session
  (Driver info: chromedriver=2.30.477690 (c53f4ad87510ee97b5c3425a14c0e79780cdf262),platform=Mac OS X 10.12.5 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 170 milliseconds
Build info: version: '3.3.1', revision: '5234b325d5', time: '2017-03-10 09:10:29 +0000'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.30.477690 (c53f4ad87510ee97b5c3425a14c0e79780cdf262), userDataDir=/var/folders/1j/tdgn9dcn6d9g9dcd3fs8nj8c0000gn/T/.org.chromium.Chromium.w0MnZI}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=59.0.3071.86, platform=MAC, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=}]
Session ID: a6bac4fb4281b2071959477ddef73095

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:216)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:168)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:638)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:274)
	at org.openqa.selenium.remote.RemoteWebElement.isEnabled(RemoteWebElement.java:148)
	at org.fluentlenium.core.proxy.ComponentHandler.isStale(ComponentHandler.java:52)
	at org.fluentlenium.core.proxy.AbstractLocatorHandler.getLocatorResult(AbstractLocatorHandler.java:135)
	at org.fluentlenium.core.proxy.ComponentHandler.invoke(ComponentHandler.java:96)
	at com.sun.proxy.$Proxy11.getWrappedElement(Unknown Source)
	at org.fluentlenium.core.components.ComponentsManager.unwrapElement(ComponentsManager.java:169)
	at org.fluentlenium.core.components.ComponentsManager.register(ComponentsManager.java:118)
	at org.fluentlenium.core.components.ComponentsManager.newComponent(ComponentsManager.java:71)
	at org.fluentlenium.core.components.LazyComponentList.transformList(LazyComponentList.java:52)
	at org.fluentlenium.core.components.LazyComponentList.getList(LazyComponentList.java:27)
	at org.fluentlenium.core.components.LazyComponentList.isEmpty(LazyComponentList.java:26)
	at org.fluentlenium.core.domain.DelegatingList.isEmpty(DelegatingList.java:13)
	at org.fluentlenium.core.conditions.AtLeastOneElementConditions.lambda$buildAtLeastOnePredicate$0(AtLeastOneElementConditions.java:47)
	at org.fluentlenium.core.conditions.AtLeastOneElementConditions.verify(AtLeastOneElementConditions.java:35)
	at org.fluentlenium.core.conditions.AbstractFluentListConditions.present(AbstractFluentListConditions.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.fluentlenium.core.conditions.wait.WaitConditionInvocationHandler$2.apply(WaitConditionInvocationHandler.java:216)
	at org.fluentlenium.core.conditions.wait.WaitConditionInvocationHandler$2.apply(WaitConditionInvocationHandler.java:212)
	at org.fluentlenium.core.conditions.wait.WaitConditionInvocationHandler.lambda$until$0(WaitConditionInvocationHandler.java:156)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:209)
	at org.fluentlenium.core.wait.FluentWait.untilPredicate(FluentWait.java:131)
	at org.fluentlenium.core.conditions.wait.WaitConditionInvocationHandler.until(WaitConditionInvocationHandler.java:144)
	at org.fluentlenium.core.conditions.wait.WaitConditionInvocationHandler.until(WaitConditionInvocationHandler.java:175)
	at org.fluentlenium.core.conditions.wait.WaitConditionInvocationHandler.waitForCondition(WaitConditionInvocationHandler.java:212)
	at org.fluentlenium.core.conditions.wait.WaitConditionInvocationHandler.invoke(WaitConditionInvocationHandler.java:190)
	at com.sun.proxy.$Proxy8.present(Unknown Source)
	at Example.GoogleTest(Example.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

Jun 17, 2017 3:21:39 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {}->http://localhost:6415: Broken pipe (Write failed)
Jun 17, 2017 3:21:39 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://localhost:6415
[NID=105=MDvPedCcTG8Btw6CP5O4e6nNL_T0pHtFhW-WtIVQ5eJHj3uIl0lYREMy00zvK8kVAR5zitZqLr7fre0nmLDdXJ7DUQgJtiiMRRLm2MYyarFsxmo8-WPgwQrwkN4gnr0lQgVxLsPB7B3hpfbh9g; expires=Sun, 17 Dec 2017 02:21:39 EST; path=/; domain=.google.com]
```

![screen shot 2017-06-17 at 3 25 55 pm](https://user-images.githubusercontent.com/25773713/27255670-4c98991a-5371-11e7-8418-5bd99e87bdcf.png)

**Comment by filipcynarski** [comment]
@tienlong826 thank you for digging deeper I see it is not able to create separate webdriver session for thread.

I've played w/ `driverLifecycle` flag a little bit but it won't help

``java
@FluentConfiguration(driverLifecycle = ConfigurationProperties.DriverLifecycle.METHOD)
public class ExampleTest extends FluentTestNg {
``

I think we can introduce the ConfigurationProperties.DriverLifecycle.THREAD to make it possible for you.

I may suggest workaround to configure it on maven level if does it work for you, please take a look here and I'll add the feature basing on your request to implement it in next release ;)

http://maven.apache.org/surefire/maven-surefire-plugin/examples/testng.html

**Comment by filipcynarski** [comment]
We should handle threading annotations and support webdriver creation on thread level, it make sense to introduce configuration parameter like this

`ConfigurationProperties.DriverLifecycle.THREAD`

**Comment by tienlong826** [comment]
@filipcynarski Thank you!

Awaiting for the new release :D

**Comment by filipcynarski** [comment]
@tienlong826 issue resolved you can check snapshot version if you would like to check
