### ISSUE TITLE
DriverLifecycle Thread is failing to detect elements intermittenly

### ISSUE THREAD

**Issue by tienlong826** [FluentLenium/FluentLenium#518]
Hi!

Upon testing the new feature, I noticed that, at times, one of the test (or multiples) will fail because it can't find an element even though the page is fully loaded.

In this case, I am using Google.com again to test.

Here's the sample code:

```
@FluentConfiguration(driverLifecycle = ConfigurationProperties.DriverLifecycle.THREAD)
public class GoogleThreadsTest extends FluentTestNg {

    @Test(invocationCount = 5, threadPoolSize = 5)
    public void firstMethod() {
        goTo("http://www.google.com");
        await().atMost(30, TimeUnit.SECONDS).until($(".gsfi")).present();
    }

    @AfterMethod
    public void afterMethod() {
        assertThat(window().title()).isEqualTo("Google");
    }
}
```

I can change it to 60 seconds and it does the same. Sometime they all pass, sometimes not.

This is the stacktrace:

```
[TestNG] Running:
Starting ChromeDriver 2.30.477690 (c53f4ad87510ee97b5c3425a14c0e79780cdf262) on port 43052
Only local connections are allowed.
Jul 07, 2017 8:29:03 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
Starting ChromeDriver 2.30.477690 (c53f4ad87510ee97b5c3425a14c0e79780cdf262) on port 38566
Only local connections are allowed.
Jul 07, 2017 8:29:03 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS

org.openqa.selenium.TimeoutException: Expected condition failed: Elements By.cssSelector: .gsfi (Lazy Element List) is not present (tried for 30 second(s) with 500 MILLISECONDS interval)
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.5', java.version: '1.8.0_131'
Driver info: driver.version: unknown

	at org.openqa.selenium.support.ui.FluentWait.timeoutException(FluentWait.java:264)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:232)
	at org.fluentlenium.core.wait.FluentWait.untilPredicate(FluentWait.java:131)
	at org.fluentlenium.core.conditions.wait.WaitConditionInvocationHandler.until(WaitConditionInvocationHandler.java:139)
	at org.fluentlenium.core.conditions.wait.WaitConditionInvocationHandler.until(WaitConditionInvocationHandler.java:170)
	at org.fluentlenium.core.conditions.wait.WaitConditionInvocationHandler.waitForCondition(WaitConditionInvocationHandler.java:207)
	at org.fluentlenium.core.conditions.wait.WaitConditionInvocationHandler.invoke(WaitConditionInvocationHandler.java:185)
	at com.sun.proxy.$Proxy17.present(Unknown Source)
	at org.fluentlenium.adapter.testng.integration.shareddriver.DriverPerThreadTest.firstMethod(DriverPerThreadTest.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

Starting ChromeDriver 2.30.477690 (c53f4ad87510ee97b5c3425a14c0e79780cdf262) on port 48918
Only local connections are allowed.

Jul 07, 2017 8:29:04 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
Starting ChromeDriver 2.30.477690 (c53f4ad87510ee97b5c3425a14c0e79780cdf262) on port 4448
Only local connections are allowed.
Jul 07, 2017 8:29:05 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
Starting ChromeDriver 2.30.477690 (c53f4ad87510ee97b5c3425a14c0e79780cdf262) on port 11957
Only local connections are allowed.
Jul 07, 2017 8:29:06 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS

===============================================
Default Suite
Total tests run: 5, Failures: 1, Skips: 0
===============================================
```

**Comment by filipcynarski** [comment]
It is passing on my laptop, could you please paste you maven config as well?

I've reduced the await to 1 sec and it is also passing

```java
        await().atMost(1, TimeUnit.SECONDS).until($(".gsfi")).present();
```

**Comment by filipcynarski** [comment]
@tienlong826 awaiting for more details

**Comment by tienlong826** [comment]
@filipcynarski Weird that it passed for you.
I took the pom config directly from Fluent's project as a test
But here is what I have:

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.fluentlenium</groupId>
        <artifactId>fluentlenium-parent</artifactId>
        <version>3.2.1-SNAPSHOT</version>
    </parent>

    <artifactId>fluentlenium-testng</artifactId>
    <name>FluentLenium TestNG</name>
    <description>TestNG Adapter for FluentLenium</description>

    <dependencies>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-chrome-driver</artifactId>
            <version>3.3.1</version>
        </dependency>
        <dependency>
            <groupId>org.fluentlenium</groupId>
            <artifactId>fluentlenium-core</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>htmlunit-driver</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>xml-apis</groupId>
            <artifactId>xml-apis</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.fluentlenium</groupId>
            <artifactId>fluentlenium-assertj</artifactId>
            <version>${project.version}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <artifactId>maven-failsafe-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>integration-tests</id>
            <activation>
                <property>
                    <name>!skipITs</name>
                </property>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <artifactId>maven-invoker-plugin</artifactId>
                        <version>2.0.0</version>
                        <configuration>
                            <skipInstallation>${skipTests}</skipInstallation>
                            <skipInvocation>${skipTests}</skipInvocation>
                        </configuration>
                        <executions>
                            <execution>
                                <id>testng-it-install</id>
                                <goals>
                                    <goal>install</goal>
                                </goals>
                            </execution>
                            <execution>
                                <id>it-run</id>
                                <goals>
                                    <goal>run</goal>
                                </goals>
                                <configuration>
                                    <goals>
                                        <goal>clean</goal>
                                        <goal>install</goal>
                                        <goal>test</goal>
                                    </goals>
                                    <properties>
                                        <it.project.version>${project.version}</it.project.version>
                                    </properties>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>

```

**Comment by filipcynarski** [comment]
Let's use 3.3.0-SNAPSHOT instead it is building right now, I've added your case as a test for e2e tests flow so if the pull request pass it should work on your end as well.

**Comment by tienlong826** [comment]
I pulled down 3.3.0-SNAPSHOT and I ran the test again this time, they were successful 15 times. The 16th time I ran it: this happen (same issue again)

```
[TestNG] Running:
  /Users/longnguyen/Library/Caches/IntelliJIdea2017.1/temp-testng-customsuite.xml
Starting ChromeDriver 2.30.477690 (c53f4ad87510ee97b5c3425a14c0e79780cdf262) on port 31361
Only local connections are allowed.
Jul 10, 2017 11:40:13 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
Starting ChromeDriver 2.30.477690 (c53f4ad87510ee97b5c3425a14c0e79780cdf262) on port 16241
Only local connections are allowed.
Jul 10, 2017 11:40:14 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS

org.openqa.selenium.TimeoutException: Expected condition failed: Elements By.cssSelector: .gsfi (Lazy Element List) is not present (tried for 30 second(s) with 500 MILLISECONDS interval)
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'Longs-MacBook-Pro.local', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.5', java.version: '1.8.0_131'
Driver info: driver.version: unknown

	at org.openqa.selenium.support.ui.FluentWait.timeoutException(FluentWait.java:264)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:232)
	at org.fluentlenium.core.wait.FluentWait.untilPredicate(FluentWait.java:131)
	at org.fluentlenium.core.conditions.wait.WaitConditionInvocationHandler.until(WaitConditionInvocationHandler.java:139)
	at org.fluentlenium.core.conditions.wait.WaitConditionInvocationHandler.until(WaitConditionInvocationHandler.java:170)
	at org.fluentlenium.core.conditions.wait.WaitConditionInvocationHandler.waitForCondition(WaitConditionInvocationHandler.java:207)
	at org.fluentlenium.core.conditions.wait.WaitConditionInvocationHandler.invoke(WaitConditionInvocationHandler.java:185)
	at com.sun.proxy.$Proxy17.present(Unknown Source)
	at org.fluentlenium.e2e.test.GoogleThreadsTest.firstMethod(GoogleThreadsTest.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)


org.openqa.selenium.TimeoutException: Expected condition failed: Elements By.cssSelector: .gsfi (Lazy Element List) is not present (tried for 30 second(s) with 500 MILLISECONDS interval)
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'Longs-MacBook-Pro.local', ip: 'fe80:0:0:0:88:7df3:d024:691c%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.5', java.version: '1.8.0_131'
Driver info: driver.version: unknown

	at org.openqa.selenium.support.ui.FluentWait.timeoutException(FluentWait.java:264)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:232)
	at org.fluentlenium.core.wait.FluentWait.untilPredicate(FluentWait.java:131)
	at org.fluentlenium.core.conditions.wait.WaitConditionInvocationHandler.until(WaitConditionInvocationHandler.java:139)
	at org.fluentlenium.core.conditions.wait.WaitConditionInvocationHandler.until(WaitConditionInvocationHandler.java:170)
	at org.fluentlenium.core.conditions.wait.WaitConditionInvocationHandler.waitForCondition(WaitConditionInvocationHandler.java:207)
	at org.fluentlenium.core.conditions.wait.WaitConditionInvocationHandler.invoke(WaitConditionInvocationHandler.java:185)
	at com.sun.proxy.$Proxy17.present(Unknown Source)
	at org.fluentlenium.e2e.test.GoogleThreadsTest.firstMethod(GoogleThreadsTest.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

Starting ChromeDriver 2.30.477690 (c53f4ad87510ee97b5c3425a14c0e79780cdf262) on port 38919
Only local connections are allowed.
Jul 10, 2017 11:40:15 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
Starting ChromeDriver 2.30.477690 (c53f4ad87510ee97b5c3425a14c0e79780cdf262) on port 32582
Only local connections are allowed.
Jul 10, 2017 11:40:16 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
Starting ChromeDriver 2.30.477690 (c53f4ad87510ee97b5c3425a14c0e79780cdf262) on port 34554
Only local connections are allowed.
Jul 10, 2017 11:40:17 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS

===============================================
Default Suite
Total tests run: 5, Failures: 2, Skips: 0
===============================================


Process finished with exit code 0
```

**Comment by filipcynarski** [comment]
Looks like more likely network issue not the FluentLenium issue, I ran the tests many time locally and got this issue when I had too much chrome browsers and chrome crashed because of too many browser windows opened.

Are you satisfied by my answer and shall we mark it as ready to merge?

**Comment by tienlong826** [comment]
That very weird. But yeah you can go ahead and mark it as ready to merge.]

Thanks for looking into it :D

**Comment by filipcynarski** [comment]
Chrome is sometimes fail to start or hangs if you run to many instances of those browser I've added another task: #520 which should help us to make it more reliable.
