### ISSUE TITLE
Does the quickstart project work?

### ISSUE THREAD

**Issue by timdodd** [FluentLenium/FluentLenium#543]
I pulled down the git repo and opened the quickstart project in eclipse. I noticed the DuckDuckGoTest is in a folder named 'org.fluentlenium.examples.quickstart' rather than org/fluentlenium/examples/quickstart. I moved the test to the default package to run it and i'm getting the following exception (also getting the same exception command line executing mvn test):

```
java.lang.NoClassDefFoundError: org/openqa/selenium/remote/JsonException
	at org.fluentlenium.configuration.DefaultConfigurationFactory.newConfiguration(DefaultConfigurationFactory.java:39)
	at org.fluentlenium.configuration.ConfigurationFactoryProvider.getConfigurationFactory(ConfigurationFactoryProvider.java:24)
	at org.fluentlenium.configuration.ConfigurationFactoryProvider.newConfiguration(ConfigurationFactoryProvider.java:46)
	at org.fluentlenium.adapter.FluentAdapter.<init>(FluentAdapter.java:23)
	at org.fluentlenium.adapter.FluentTestRunnerAdapter.<init>(FluentTestRunnerAdapter.java:55)
	at org.fluentlenium.adapter.FluentTestRunnerAdapter.<init>(FluentTestRunnerAdapter.java:36)
	at org.fluentlenium.adapter.FluentTestRunnerAdapter.<init>(FluentTestRunnerAdapter.java:27)
	at org.fluentlenium.adapter.junit.FluentTest.<init>(FluentTest.java:15)
	at DuckDuckGoTest.<init>(DuckDuckGoTest.java:9)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:217)
	at org.junit.runners.BlockJUnit4ClassRunner$1.runReflectiveCall(BlockJUnit4ClassRunner.java:266)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.fluentlenium.adapter.junit.FluentTest$2$1.evaluate(FluentTest.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.lang.ClassNotFoundException: org.openqa.selenium.remote.JsonException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 33 more


```

**Comment by timdodd** [comment]
UPDATE: I added selenium-server and selenium-remote-driver and newWebDriver return a configured PhantomJSDriver and the test runs. Presumably i'm doing something wrong though. I'm assuming the quickstart is supposed to work out of the box?

**Comment by jaipaddy** [comment]
I face the same issue, the quickstart is not working

**Comment by gkiszczak** [comment]
@jaipaddy could you please show me your pom.xml file? Are you facing exactly the same error? 
I'm afraid selenium 3.7.1 introduced some breaking changes. Please try version 3.5.3.
We will try to upgrade FluentLenium to latest selenium version as fast as possible.

**Comment by filipcynarski** [comment]
no update from reporter closing the issue.
