### ISSUE TITLE
Browser failed to start with org.openqa.selenium.WebDriverException Exception

### ISSUE THREAD

**Issue by Gichure** [FluentLenium/FluentLenium#550]
I am trying out FluentLenium on a Maven project and below is the sample code I'm running
```java 
@Test
    public void loginShouldLoadLoginPage() {
        goTo(getUrl());
        $("#username").fill().with("TQUEST");
        $("#password").fill().with("Tquest123#@!");
        $("#pgl1").submit();
        await().atMost(5, TimeUnit.SECONDS).until(el("#pgl1")).not().present();
        assertThat(window().title()).contains("FluentLenium");
    }

    public String getUrl() {
	        return "http://10.176.18.51:7001/TQTEST";
    }
```

However, on running the test case, I am getting the below exception;
org.openqa.selenium.WebDriverException: Browser failed to start, test [ loginShouldLoadLoginPage(package.GISLoginTest) ] execution interrupted.
Caused by: [ java.lang.ExceptionInInitializerError]
Build info: version: '2.25.0', revision: '17482', time: '2012-07-18 22:18:01'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_144'
Driver info: driver.version: unknown
	at org.fluentlenium.adapter.FluentTestRunnerAdapter.starting(FluentTestRunnerAdapter.java:124)
	at org.fluentlenium.adapter.junit.FluentTest.access$000(FluentTest.java:15)
	at org.fluentlenium.adapter.junit.FluentTest$1.starting(FluentTest.java:25)
	at org.fluentlenium.adapter.junit.FluentTestRule$1.evaluate(FluentTestRule.java:43)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.fluentlenium.adapter.junit.FluentTest$2$1.evaluate(FluentTest.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:539)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:761)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:461)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:207)

I guess the issue is with Driver loading, how do I sort this on Maven project running on Windows 10 OS?

**Comment by filipcynarski** [comment]
@Gichure I see you mixed Test class w/ Page Class you need to create two classes at least.

First is a test class like this:

```
public class MyTestClass extends FluentTest {
   @Page
   MyPageClass myPage;

   @Test
   public void loginShouldLoadLoginPage() {
        goTo(myPage);
        $("#username").fill().with("TQUEST");
        $("#password").fill().with("Tquest123#@!");
        $("#pgl1").submit();
        await().atMost(5, TimeUnit.SECONDS).until(el("#pgl1")).not().present();
        assertThat(window().title()).contains("FluentLenium");
    }
}
```

and the second is a Page class

```
@PageUrl("http://10.176.18.51:7001/TQTEST")
public class MyPageClass extends FluentPage {

}
```

Please take a look on documentation and examples to have running example.

**Comment by Gichure** [comment]
Hello @filipcynarski , I'm following this https://github.com/FluentLenium/FluentLenium/tree/master/examples/quickstart/src/test/java/org.fluentlenium.examples.quickstart quickstart demo and even following you suggestion, I still get the exception..
Could there be extra configuration required for Maven project?

**Comment by filipcynarski** [comment]
@Gichure could you please attach your code here? I can review it, exception seems unrelated to FluentLenim rather to environment where you are trying to run your test.

**Comment by Gichure** [comment]
Test Class
`import static org.assertj.core.api.Assertions.assertThat;

import java.util.concurrent.TimeUnit;

import org.fluentlenium.adapter.junit.FluentTest;
import org.fluentlenium.core.annotation.Page;
import org.fluentlenium.core.hook.wait.Wait;
import org.junit.Test;

/**
 * @author Paul
 * Oct 31, 2017
 */
@Wait
public class GISLoginTest extends FluentTest {
	   @Page
	   MyPageClass myPage;

	   @Test
	   public void loginShouldLoadLoginPage() {
	        goTo(myPage);
	        $("#username").fill().with("TQUEST");
	        $("#password").fill().with("Tquest123#@!");
	        $("#pgl1").submit();
	        await().atMost(5, TimeUnit.SECONDS).until(el("#pgl1")).not().present();
	        assertThat(window().title()).contains("TurnQuest");
	    }
	
}
`

POM.XML

`<dependencies>
	 <dependency>
            <groupId>org.fluentlenium</groupId>
            <artifactId>fluentlenium-junit</artifactId>
            <version>${fluentlenium.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.fluentlenium</groupId>
            <artifactId>fluentlenium-assertj</artifactId>
            <version>${fluentlenium.version}</version>
            <scope>test</scope>
		</dependency>
        
		 <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>htmlunit-driver</artifactId>
            <version>2.26</version>
            <scope>test</scope>
		</dependency>
		<dependency>
		    <groupId>xml-apis</groupId>
		    <artifactId>xml-apis</artifactId>
		    <version>1.4.01</version>
		    <scope>test</scope>
		</dependency>
        
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.12</version>
      <scope>test</scope>
    </dependency>
</dependencies>`


<fluentlenium.version>3.4.1</fluentlenium.version>

**Comment by filipcynarski** [comment]
@Gichure please check the attached archive out
[issuereproduce.zip](https://github.com/FluentLenium/FluentLenium/files/1431146/issuereproduce.zip)

**Comment by filipcynarski** [comment]
@Gichure is the issue resolved on your end?

**Comment by Gichure** [comment]
@filipcynarski it seems it is a configuration issue and not FluentLenium issue at all. Thank you for your suggestions and time.
