### ISSUE TITLE
Can't get basic test to work

### ISSUE THREAD

**Issue by sMteX** [FluentLenium/FluentLenium#557]
Hello!

I've tried using FluentLenium and I can't seem to get even a simple test to work. I've tried going by the examples, and just an endless stream of exception thrown at me, and after googling for several hours I'm drowning in dependencies I don't even know if are used or necessary. Please for the love of all that's holy could someone point me in the right direction?

(hopefully) relevant dependencies in pom.xml:
```xml
        <dependency>
            <groupId>org.fluentlenium</groupId>
            <artifactId>fluentlenium-core</artifactId>
            <version>3.4.1</version>
        </dependency>

        <dependency>
            <groupId>org.fluentlenium</groupId>
            <artifactId>fluentlenium-junit</artifactId>
            <version>3.4.1</version>
        </dependency>

        <dependency>
            <groupId>org.fluentlenium</groupId>
            <artifactId>fluentlenium-assertj</artifactId>
            <version>3.4.1</version>
        </dependency>

        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-chrome-driver</artifactId>
            <version>3.7.0</version>
        </dependency>

        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-htmlunit-driver</artifactId>
            <version>2.52.0</version>
        </dependency>

        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-api</artifactId>
            <version>3.4.0</version>
        </dependency>

        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>3.7.1</version>
        </dependency>
```
I tried to pull the dependencies from mvnrepository.com to get the latest version, but even if I use those you specify in README.md, it's not working.

Test file:
```java
import com.wcff.tasks.ui.pages.RegisterPage;
import org.fluentlenium.adapter.junit.FluentTest;
import org.fluentlenium.configuration.FluentConfiguration;
import org.fluentlenium.core.annotation.Page;
import org.junit.Test;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

@FluentConfiguration(webDriver = "chrome")
public class RegisterTest extends FluentTest {

    @Override
    public WebDriver newWebDriver() {
        System.setProperty("webdriver.chrome.driver", System.getProperty("user.dir") + "\\drivers\\chromedriver.exe");
        return new ChromeDriver();
    }

    @Page
    private RegisterPage page;

    @Test
    public void nameShouldNotBeEmpty() {
        goTo(page)
                .typeInName("")
                .typeInSurname("Smith")
                .typeInEmail("john@smith.com")
                .typeInPassword("00000")
                .submitForm()
                .assertNameCantBeEmpty();
    }


}
```

I've tried doing it without the `@FluentConfiguration`, without the `@Override`, and it either can't find `MutableCapabilities` (which I solved by adding `selenium-api` I think) or there's the `ChromeDriver` missing (even though the example said nothing about these issues) or now there's `LoggingHandler` missing (`NoClassDefFoundError`) and who knows what error is around the corner.

Any help preventing me from ending in mental asylum would be gladly appreciated. Thank you for your time.

EDIT: Stack trace from the test:
```
org.openqa.selenium.WebDriverException: Browser failed to start, test [ nameShouldNotBeEmpty(com.wcff.tasks.ui.RegisterTest) ] execution interrupted.
Caused by: [ java.lang.NoClassDefFoundError: org/openqa/selenium/logging/LoggingHandler]
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'SMTEX-PC', ip: '192.168.1.9', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_152'
Driver info: driver.version: unknown

	at org.fluentlenium.adapter.FluentTestRunnerAdapter.starting(FluentTestRunnerAdapter.java:124)
	at org.fluentlenium.adapter.junit.FluentTest.access$000(FluentTest.java:15)
	at org.fluentlenium.adapter.junit.FluentTest$1.starting(FluentTest.java:25)
	at org.fluentlenium.adapter.junit.FluentTestRule$1.evaluate(FluentTestRule.java:43)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.fluentlenium.adapter.junit.FluentTest$2$1.evaluate(FluentTest.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

**Comment by Toilal** [comment]
There's many dependency issues in your configuration, that's why it's not working.

First of all, [org.seleniumhq.selenium:selenium-htmlunit-driver](https://mvnrepository.com/artifact/org.seleniumhq.selenium/selenium-htmlunit-driver) is deprecated, and you should use [https://mvnrepository.com/artifact/org.seleniumhq.selenium/selenium-htmlunit] as defined in quickstart example. If you want to run tests againt chrome only, you can simply remove this dependency.

Then, current version of fluentlenium is build against [selenium 3.5.3](https://github.com/FluentLenium/FluentLenium/blob/7f21e96f02524ea4d72f6c7905b47158fb492c29/pom.xml#L97), so you should use this version for chrome driver.

Finally, you don't have to import other selenium dependencies (api, or anything else), only browser drivers with the right version. Required dependencies are declared with right versions as transient dependencies of fluentlenium-junit module.

Here's a quickwin to avoid mental asylum: copy/paste [the quickstart example](https://github.com/FluentLenium/FluentLenium/tree/develop/examples/quickstart), replace the htmunit-driver with selenium-chrome-driver 3.5.3, and it should just work and run chrome instead of htmlunit.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <artifactId>fluentlenium-examples-quickstart</artifactId>
    <groupId>org.fluentlenium</groupId>
    <version>3.4.1</version>

    <properties>
        <!-- Configure this property to latest available version -->
        <fluentlenium.version>3.4.1</fluentlenium.version>
    </properties>

    <name>FluentLenium Examples Quickstart</name>

    <build>
        <plugins>
            <plugin>
                <artifactId>maven-deploy-plugin</artifactId>
                <version>2.8.2</version>
                <configuration>
                    <skip>true</skip>
                </configuration>
            </plugin>
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.6.0</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <dependency>
            <groupId>org.fluentlenium</groupId>
            <artifactId>fluentlenium-junit</artifactId>
            <version>${fluentlenium.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.fluentlenium</groupId>
            <artifactId>fluentlenium-assertj</artifactId>
            <version>${fluentlenium.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-chrome-driver</artifactId>
            <version>3.5.3</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

</project>
```

I just tested this configuration and it's running fine.

**Comment by filipcynarski** [comment]
@sMteX I'm planning to change website and examples to be more user friendly in the 3.5 release I have a feeling that many users struggle w/ those examples, thank you for your issue it will be a good input for me to make our documentation easier to follow-up, please let us know if @Toilal suggestions helped you to sort your issue out

**Comment by Toilal** [comment]
It would be great. Problem here is that the classpath can be easily messed up when including dependencies with wrong versions.

**Comment by sMteX** [comment]
Thank you for the quick responses and some clarification as to *why?*.
I tried opening up a blank test project, copypasting the DuckDuckGoTest and pom.xml, but I'm still getting `Can't create WebDriver instance`.

Stack trace here:
```
org.openqa.selenium.WebDriverException: Browser failed to start, test [ titleOfDuckDuckGoShouldContainSearchQueryName(test.DuckDuckGoTest) ] execution interrupted.
Caused by: [ org.fluentlenium.configuration.ConfigurationException: Can't create new WebDriver instance]
Build info: version: '3.5.3', revision: 'a88d25fe6b', time: '2017-08-29T12:42:44.417Z'
System info: host: 'SMTEX-PC', ip: '192.168.1.9', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_152'
Driver info: driver.version: unknown

	at org.fluentlenium.adapter.FluentTestRunnerAdapter.starting(FluentTestRunnerAdapter.java:124)
	at org.fluentlenium.adapter.junit.FluentTest.access$000(FluentTest.java:15)
	at org.fluentlenium.adapter.junit.FluentTest$1.starting(FluentTest.java:25)
	at org.fluentlenium.adapter.junit.FluentTestRule$1.evaluate(FluentTestRule.java:43)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.fluentlenium.adapter.junit.FluentTest$2$1.evaluate(FluentTest.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

**Comment by Toilal** [comment]
[ChromeDriver](https://sites.google.com/a/chromium.org/chromedriver/) must be available in the path too.

**Comment by sMteX** [comment]
Where should it be? Would it be possible to *not* place it in the path but to keep it somewhere as a folder in the project? (like I tried, folder "drivers" on the same level as pom.xml) I'd like if my coworkers wouldn't have to make any changes to their system to use these tests.

**Comment by Toilal** [comment]
In fact, fluentlenium init code hide the real error message. I'll fix this, but the real error is :+1: 

The path to the driver executable must be set by the webdriver.chrome.driver system property; for more information, see https://github.com/SeleniumHQ/selenium/wiki/ChromeDriver. The latest version can be downloaded from http://chromedriver.storage.googleapis.com/index.html

So you can set it by setting the system property webdriver.chrome.driver (`-Dwebdriver.chrome.driver=/home/user/bin/chromedriver` when running the java process)

**Comment by sMteX** [comment]
Hmm, when I tried 
```java
public DuckDuckGoTest() {
        super();
        System.setProperty("webdriver.chrome.driver", System.getProperty("user.dir") + "\\drivers\\chromedriver.exe");
    }
```
It finally worked. But when I do the same to the real project (commented out the old dependencies, pasted those that worked for me now), it's still stuck at the same exception.

**Comment by Toilal** [comment]
Please paste output of `mvn dependency:tree`.

**Comment by sMteX** [comment]
Sorry, it's probably a mess, I've never worked with Maven, Spring (Boot) before, don't know what's necessary or not. Here it is (the one that doesn't work):

```
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building 2Do List 1.0
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-dependency-plugin:2.10:tree (default-cli) @ tasks ---
[INFO] com.wcff:tasks:jar:1.0
[INFO] +- org.springframework.boot:spring-boot-starter-data-jpa:jar:1.5.7.RELEASE:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter:jar:1.5.7.RELEASE:compile
[INFO] |  |  +- org.springframework.boot:spring-boot:jar:1.5.7.RELEASE:compile
[INFO] |  |  +- org.springframework.boot:spring-boot-autoconfigure:jar:1.5.7.RELEASE:compile
[INFO] |  |  +- org.springframework.boot:spring-boot-starter-logging:jar:1.5.7.RELEASE:compile
[INFO] |  |  |  +- ch.qos.logback:logback-classic:jar:1.1.11:compile
[INFO] |  |  |  |  \- ch.qos.logback:logback-core:jar:1.1.11:compile
[INFO] |  |  |  +- org.slf4j:jul-to-slf4j:jar:1.7.25:compile
[INFO] |  |  |  \- org.slf4j:log4j-over-slf4j:jar:1.7.25:compile
[INFO] |  |  \- org.yaml:snakeyaml:jar:1.17:runtime
[INFO] |  +- org.springframework.boot:spring-boot-starter-aop:jar:1.5.7.RELEASE:compile
[INFO] |  |  \- org.aspectj:aspectjweaver:jar:1.8.10:compile
[INFO] |  +- org.hibernate:hibernate-core:jar:5.0.12.Final:compile
[INFO] |  |  +- org.jboss.logging:jboss-logging:jar:3.3.1.Final:compile
[INFO] |  |  +- org.hibernate.javax.persistence:hibernate-jpa-2.1-api:jar:1.0.0.Final:compile
[INFO] |  |  +- org.javassist:javassist:jar:3.21.0-GA:compile
[INFO] |  |  +- antlr:antlr:jar:2.7.7:compile
[INFO] |  |  +- org.jboss:jandex:jar:2.0.0.Final:compile
[INFO] |  |  +- dom4j:dom4j:jar:1.6.1:compile
[INFO] |  |  \- org.hibernate.common:hibernate-commons-annotations:jar:5.0.1.Final:compile
[INFO] |  +- org.hibernate:hibernate-entitymanager:jar:5.0.12.Final:compile
[INFO] |  +- javax.transaction:javax.transaction-api:jar:1.2:compile
[INFO] |  +- org.springframework.data:spring-data-jpa:jar:1.11.7.RELEASE:compile
[INFO] |  |  +- org.springframework.data:spring-data-commons:jar:1.13.7.RELEASE:compile
[INFO] |  |  +- org.springframework:spring-orm:jar:4.3.11.RELEASE:compile
[INFO] |  |  +- org.springframework:spring-tx:jar:4.3.11.RELEASE:compile
[INFO] |  |  \- org.slf4j:jcl-over-slf4j:jar:1.7.25:compile
[INFO] |  \- org.springframework:spring-aspects:jar:4.3.11.RELEASE:compile
[INFO] +- org.springframework.boot:spring-boot-starter-jdbc:jar:1.5.7.RELEASE:compile
[INFO] |  +- org.apache.tomcat:tomcat-jdbc:jar:8.5.20:compile
[INFO] |  |  \- org.apache.tomcat:tomcat-juli:jar:8.5.20:compile
[INFO] |  \- org.springframework:spring-jdbc:jar:4.3.11.RELEASE:compile
[INFO] +- org.springframework.boot:spring-boot-starter-security:jar:1.5.7.RELEASE:compile
[INFO] |  +- org.springframework:spring-aop:jar:4.3.11.RELEASE:compile
[INFO] |  +- org.springframework.security:spring-security-config:jar:4.2.3.RELEASE:compile
[INFO] |  \- org.springframework.security:spring-security-web:jar:4.2.3.RELEASE:compile
[INFO] +- org.springframework.boot:spring-boot-starter-thymeleaf:jar:1.5.7.RELEASE:compile
[INFO] |  +- org.thymeleaf:thymeleaf-spring4:jar:2.1.5.RELEASE:compile
[INFO] |  |  \- org.thymeleaf:thymeleaf:jar:2.1.5.RELEASE:compile
[INFO] |  |     +- ognl:ognl:jar:3.0.8:compile
[INFO] |  |     \- org.unbescape:unbescape:jar:1.1.0.RELEASE:compile
[INFO] |  \- nz.net.ultraq.thymeleaf:thymeleaf-layout-dialect:jar:1.4.0:compile
[INFO] |     \- org.codehaus.groovy:groovy:jar:2.4.12:compile
[INFO] +- org.springframework.boot:spring-boot-starter-web:jar:1.5.7.RELEASE:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-tomcat:jar:1.5.7.RELEASE:compile
[INFO] |  |  +- org.apache.tomcat.embed:tomcat-embed-core:jar:8.5.20:compile
[INFO] |  |  +- org.apache.tomcat.embed:tomcat-embed-el:jar:8.5.20:compile
[INFO] |  |  \- org.apache.tomcat.embed:tomcat-embed-websocket:jar:8.5.20:compile
[INFO] |  +- org.hibernate:hibernate-validator:jar:5.3.5.Final:compile
[INFO] |  |  +- javax.validation:validation-api:jar:1.1.0.Final:compile
[INFO] |  |  \- com.fasterxml:classmate:jar:1.3.4:compile
[INFO] |  +- org.springframework:spring-web:jar:4.3.11.RELEASE:compile
[INFO] |  \- org.springframework:spring-webmvc:jar:4.3.11.RELEASE:compile
[INFO] +- javax.xml.bind:jaxb-api:jar:2.2:compile
[INFO] |  +- javax.xml.stream:stax-api:jar:1.0-2:compile
[INFO] |  \- javax.activation:activation:jar:1.1:compile
[INFO] +- net.sourceforge.nekohtml:nekohtml:jar:1.9.14:compile
[INFO] |  \- xerces:xercesImpl:jar:2.9.1:compile
[INFO] |     \- xml-apis:xml-apis:jar:1.4.01:compile
[INFO] +- org.thymeleaf.extras:thymeleaf-extras-springsecurity4:jar:2.1.3.RELEASE:compile
[INFO] |  \- org.slf4j:slf4j-api:jar:1.7.25:compile
[INFO] +- com.fasterxml.jackson.core:jackson-core:jar:2.8.10:compile
[INFO] +- org.springframework:spring-messaging:jar:4.3.11.RELEASE:compile
[INFO] |  +- org.springframework:spring-beans:jar:4.3.11.RELEASE:compile
[INFO] |  +- org.springframework:spring-context:jar:4.3.11.RELEASE:compile
[INFO] |  \- org.springframework:spring-core:jar:4.3.11.RELEASE:compile
[INFO] +- com.fasterxml.jackson.core:jackson-databind:jar:2.8.10:compile
[INFO] |  \- com.fasterxml.jackson.core:jackson-annotations:jar:2.8.0:compile
[INFO] +- org.springframework.security:spring-security-messaging:jar:4.2.3.RELEASE:compile
[INFO] |  +- aopalliance:aopalliance:jar:1.0:compile
[INFO] |  +- org.springframework.security:spring-security-core:jar:4.2.3.RELEASE:compile
[INFO] |  \- org.springframework:spring-expression:jar:4.3.11.RELEASE:compile
[INFO] +- org.fluentlenium:fluentlenium-junit:jar:3.4.1:test
[INFO] |  \- org.fluentlenium:fluentlenium-core:jar:3.4.1:test
[INFO] |     +- org.seleniumhq.selenium:selenium-support:jar:2.53.1:test
[INFO] |     +- org.atteo.classindex:classindex:jar:3.4:test
[INFO] |     +- commons-io:commons-io:jar:2.5:test
[INFO] |     \- org.apache.commons:commons-lang3:jar:3.4:test
[INFO] +- org.fluentlenium:fluentlenium-assertj:jar:3.4.1:test
[INFO] |  \- org.assertj:assertj-core:jar:2.6.0:test
[INFO] +- junit:junit:jar:4.12:test
[INFO] |  \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] +- org.seleniumhq.selenium:selenium-chrome-driver:jar:3.5.3:test
[INFO] |  +- org.seleniumhq.selenium:selenium-api:jar:2.53.1:test
[INFO] |  +- org.seleniumhq.selenium:selenium-remote-driver:jar:2.53.1:test
[INFO] |  +- cglib:cglib-nodep:jar:3.2.4:test
[INFO] |  +- org.apache.commons:commons-exec:jar:1.3:test
[INFO] |  +- commons-codec:commons-codec:jar:1.10:test
[INFO] |  +- commons-logging:commons-logging:jar:1.2:test
[INFO] |  +- com.google.code.gson:gson:jar:2.8.1:test
[INFO] |  +- com.google.guava:guava:jar:23.0:test
[INFO] |  |  +- com.google.code.findbugs:jsr305:jar:1.3.9:test
[INFO] |  |  +- com.google.errorprone:error_prone_annotations:jar:2.0.18:test
[INFO] |  |  +- com.google.j2objc:j2objc-annotations:jar:1.1:test
[INFO] |  |  \- org.codehaus.mojo:animal-sniffer-annotations:jar:1.14:test
[INFO] |  +- org.apache.httpcomponents:httpclient:jar:4.5.3:test
[INFO] |  +- org.apache.httpcomponents:httpcore:jar:4.4.6:test
[INFO] |  +- net.java.dev.jna:jna:jar:4.2.2:test
[INFO] |  \- net.java.dev.jna:jna-platform:jar:4.1.0:test
[INFO] +- mysql:mysql-connector-java:jar:5.1.44:runtime
[INFO] +- org.springframework.boot:spring-boot-starter-test:jar:1.5.7.RELEASE:test
[INFO] |  +- org.springframework.boot:spring-boot-test:jar:1.5.7.RELEASE:test
[INFO] |  +- org.springframework.boot:spring-boot-test-autoconfigure:jar:1.5.7.RELEASE:test
[INFO] |  +- com.jayway.jsonpath:json-path:jar:2.2.0:test
[INFO] |  |  \- net.minidev:json-smart:jar:2.2.1:test
[INFO] |  |     \- net.minidev:accessors-smart:jar:1.1:test
[INFO] |  |        \- org.ow2.asm:asm:jar:5.0.3:test
[INFO] |  +- org.mockito:mockito-core:jar:1.10.19:test
[INFO] |  |  \- org.objenesis:objenesis:jar:2.1:test
[INFO] |  +- org.hamcrest:hamcrest-library:jar:1.3:test
[INFO] |  +- org.skyscreamer:jsonassert:jar:1.4.0:test
[INFO] |  |  \- com.vaadin.external.google:android-json:jar:0.0.20131108.vaadin1:test
[INFO] |  \- org.springframework:spring-test:jar:4.3.11.RELEASE:test
[INFO] +- org.springframework.security:spring-security-test:jar:4.2.3.RELEASE:test
[INFO] \- org.springframework.boot:spring-boot-starter-websocket:jar:1.5.7.RELEASE:compile
[INFO]    \- org.springframework:spring-websocket:jar:4.3.11.RELEASE:compile
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.158 s
[INFO] Finished at: 2017-11-07T23:15:19+01:00
[INFO] Final Memory: 24M/309M
[INFO] ------------------------------------------------------------------------
```

**Comment by Toilal** [comment]
I think I already hit this issue with some Spring dependencies. One of the spring parent pom.xml sets a `selenium.version` to `2.53.1`, that breaks fluentlenium parent pom configuration.

Please try to set `selenium.version` `3.5.3` in `properties` tag of your own project `pom.xml`. It's a bit weird but properties defined in parent pom.xml files can shadow themselves, and forcing it inside you own project will override any other defined values.

```
<properties>
  <selenium.version>3.5.3</selenium.version>
</properties>
```

**Comment by Toilal** [comment]
If it fix the issue, i'll update the quickstart example to include this property and avoid any possible property shadowing.

**Comment by Toilal** [comment]
Duplicates of #457

**Comment by sMteX** [comment]
That did the trick! Thank you very much for your help, very appreciated. 😊  While we're at it, is there some trick or way how to reduce the number of dependencies, like.. *meaningfully*? For the most part I was googling and trying to glue something to the pom till it worked but it doesn't seem right.

**Comment by Toilal** [comment]
Can you try to replace with this:

<properties>
  <selenium.version>${selenium.version}</selenium.version>
</properties>

Does it still work ?

We will add mentions to WebDrivers binaries in the docs, true that it's missing.

**Comment by Toilal** [comment]
The best thing we could do about WebDrivers confusion would be to include this project into fluentlenium : https://github.com/bonigarcia/webdrivermanager. It can manage the download of the driver and it's configuration automatically.

**Comment by sMteX** [comment]
Replace the version number for the Chrome driver with `${selenium.version}` I suppose? Yes, that worked as well. As for the Manager - anything that helps running FluentLenium out-of-the-box would help I think.

**Comment by Toilal** [comment]
Great, i'll add this into the quickstart then.

**Comment by Toilal** [comment]
But keep in mind it may break the features relying on selenium 2.53.1 inside the Spring monster. But I think you don't use them :)

**Comment by Toilal** [comment]
About the dependency weight, it doesn't seem possible to really reduce them. Maybe you can remove some Spring dependencies though.

**Comment by sMteX** [comment]
Welp, I hope not :D I'm only like half sure what I'm doing but AFAIK, Selenium is tied to testing, and from the dependency tree I haven't seen Selenium as a dependency of anything Spring-ish.

**Comment by Toilal** [comment]
The selenium version property is defined in spring boot parent. It's used in some spring testing dependencies, but you probably didn't include those dependencies inside your own project. 

But the property is still there, and that's breaking the fluentlenium pom.xml as we are using the same property name for the selenium version.

> Use spring, they said ... It will be easy, they said ...

**Comment by sMteX** [comment]
Ah, I see. Well to be honest, I don't know if having the `<parent>` set is even necessary. But seeing as I didn't include anything Spring Testing related, I think so far at least, I should be ok.

**Comment by Toilal** [comment]
Could you paste your whole pom.xml, so I can reproduce ? Or at least the spring dependencies and spring parent pom ?

**Comment by sMteX** [comment]
I don't know where could I get the spring parent pom (it's a pom generated by start.spring.io, basically pre-generates the pom based on modules you select, name, artifact ID etc.), but the whole pom.xml is here (excluding commented things):
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.wcff</groupId>
    <artifactId>tasks</artifactId>
    <version>1.0</version>

    <name>2Do List</name>
    <description>Project for RPRO1</description>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>1.5.7.RELEASE</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>

    <properties>
        <selenium.version>3.5.3</selenium.version>
        <fluentlenium.version>3.4.1</fluentlenium.version>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <maven.compiler.release>8</maven.compiler.release>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <java.version>8</java.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-jdbc</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-thymeleaf</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>javax.xml.bind</groupId>
            <artifactId>jaxb-api</artifactId>
            <version>2.2</version>
        </dependency>
        <dependency>
            <groupId>net.sourceforge.nekohtml</groupId>
            <artifactId>nekohtml</artifactId>
            <version>1.9.14</version>
        </dependency>
        <dependency>
            <groupId>org.thymeleaf.extras</groupId>
            <artifactId>thymeleaf-extras-springsecurity4</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-messaging</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-messaging</artifactId>
            <!--<version>4.2.3.RELEASE</version>-->
        </dependency>
        <dependency>
            <groupId>org.fluentlenium</groupId>
            <artifactId>fluentlenium-junit</artifactId>
            <version>${fluentlenium.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.fluentlenium</groupId>
            <artifactId>fluentlenium-assertj</artifactId>
            <version>${fluentlenium.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-chrome-driver</artifactId>
            <version>${selenium.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-websocket</artifactId>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <artifactId>maven-deploy-plugin</artifactId>
                <version>2.8.2</version>
                <configuration>
                    <skip>true</skip>
                </configuration>
            </plugin>
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.6.0</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

</project>
```
