### ISSUE TITLE
Spock -  Can't create new WebDriver instance

### ISSUE THREAD

**Issue by brunoleite** [FluentLenium/FluentLenium#569]
Hello everyone,

I am trying to use FluentLenium + Spock but I am facing a problem with webdriver. I've created a project from scratch trying to follow the official example (https://github.com/FluentLenium/FluentLenium/tree/develop/examples/spock) but I am facing the message:  Can't create new WebDriver instance
The only difference is that I am using gradle instaed of maven. Here is the code + gradle file.

Here is my DuckDuckGoSpec

```groovy
package org.fluentlenium.example.spock

import io.github.bonigarcia.wdm.FirefoxDriverManager
import org.fluentlenium.adapter.spock.FluentSpecification
import org.fluentlenium.core.hook.wait.Wait

@Wait
class DuckDuckGoSpec extends FluentSpecification {
    public static final String SEARCH_TEXT = "FluentLenium"

    void setupSpec() {
        FirefoxDriverManager.getInstance().setup()
    }

    def "Title of duck duck go"() {
        given:
        goTo("https://duckduckgo.com")

        when:
        el("#search_form_input_homepage").fill().with(SEARCH_TEXT)
        el("#search_button_homepage").submit()
        await().untilWindow(SEARCH_TEXT)

        then:
        window().title().contains(SEARCH_TEXT)
    }

}
```

Here my build.gradle

```groovy
version '1.0-SNAPSHOT'

apply plugin: 'java'
apply plugin: 'groovy'

sourceCompatibility = 1.8
targetCompatibility = 1.8

repositories {
    mavenCentral()
}

dependencies {
    compile 'org.codehaus.groovy:groovy-all:2.4.10'
    testCompile 'org.spockframework:spock-core:1.1-groovy-2.4'
    testCompile 'org.fluentlenium:fluentlenium-spock:3.4.1'
    testCompile 'org.seleniumhq.selenium:selenium-java:3.5.3'
    testCompile 'io.github.bonigarcia:webdrivermanager:2.0.1'
    testCompile 'org.slf4j:slf4j-simple:1.7.21'
}
```

Here the output:

```
org.openqa.selenium.WebDriverException: Browser failed to start, test [ Title of duck duck go(org.fluentlenium.example.spock.DuckDuckGoSpec) ] execution interrupted.
Caused by: [ org.fluentlenium.configuration.ConfigurationException: Can't create new WebDriver instance]
Build info: version: '3.5.3', revision: 'a88d25fe6b', time: '2017-08-29T12:42:44.417Z'
System info: host: 'xxxx', ip: 'xxxx', os.name: 'xxxx', os.arch: 'xxxx', os.version: 'xxx', java.version: '1.8.0_152'
Driver info: driver.version: unknown

	at org.fluentlenium.adapter.FluentTestRunnerAdapter.starting(FluentTestRunnerAdapter.java:124)
	at org.fluentlenium.adapter.spock.FluentSpecificationAdapter.specStarting(FluentSpecificationAdapter.groovy:13)
	at org.fluentlenium.adapter.spock.FluentSpecification.specStarting(FluentSpecification.groovy:19)
	at org.fluentlenium.adapter.spock.FluentSpecification$1.starting(FluentSpecification.groovy:43)
	at org.fluentlenium.adapter.junit.FluentTestRule$1.evaluate(FluentTestRule.java:43)
	at org.spockframework.runtime.extension.builtin.TestRuleInterceptor.intercept(TestRuleInterceptor.java:38)
	at org.spockframework.runtime.extension.MethodInvocation.proceed(MethodInvocation.java:87)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)


Process finished with exit code 255
```

**Comment by gkiszczak** [comment]
@brunoleite are you still facing this issue?

**Comment by brunoleite** [comment]
yep, I am @gkiszczak

**Comment by filipcynarski** [comment]
@brunoleite I've played a little bit w/ that example (it was created by contributor) and fixed the issue. Could you please check on develop branch is the issue resolved on your end?
