### ISSUE TITLE
Exception during building FleuntLenium project: java.lang.instrument.IllegalClassFormatException

### ISSUE THREAD

**Issue by koryl** [FluentLenium/FluentLenium#625]
During building  I've noticed bunch of weird looking exceptions: 
`java.lang.instrument.IllegalClassFormatException: Error while instrumenting class com/gargoylesoftware/css/parser/javacc/CSS3ParserTokenManager.
        at org.jacoco.agent.rt.internal_b0d6a23.CoverageTransformer.transform(CoverageTransformer.java:95)
        at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
        at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at com.gargoylesoftware.css.parser.javacc.CSS3Parser.<init>(CSS3Parser.java:3148)
        at com.gargoylesoftware.css.parser.javacc.CSS3Parser.<init>(CSS3Parser.java:52)
        at com.gargoylesoftware.htmlunit.html.DomNode.getSelectorList(DomNode.java:1865)
        at com.gargoylesoftware.htmlunit.html.DomNode.querySelectorAll(DomNode.java:1836)
        at org.openqa.selenium.htmlunit.HtmlUnitDriver.findElementsByCssSelector(HtmlUnitDriver.java:1315)
        at org.openqa.selenium.By$ByCssSelector.findElements(By.java:441)
        at org.openqa.selenium.htmlunit.HtmlUnitDriver.findElements(HtmlUnitDriver.java:2031)
        at org.openqa.selenium.htmlunit.HtmlUnitDriver.findElements(HtmlUnitDriver.java:803)
        at org.fluentlenium.core.search.Search$2.findElements(Search.java:103)
        at org.fluentlenium.core.proxy.AtIndexElementLocator.findElementImpl(AtIndexElementLocator.java:30)
        at org.fluentlenium.core.proxy.AtIndexElementLocator.findElement(AtIndexElementLocator.java:39)
        at org.fluentlenium.core.proxy.ComponentHandler.getLocatorResultImpl(ComponentHandler.java:68)
        at org.fluentlenium.core.proxy.ComponentHandler.getLocatorResultImpl(ComponentHandler.java:17)
        at org.fluentlenium.core.proxy.AbstractLocatorHandler.getLocatorResult(AbstractLocatorHandler.java:140)
        at org.fluentlenium.core.proxy.AbstractLocatorHandler.now(AbstractLocatorHandler.java:235)
        at org.fluentlenium.core.proxy.LocatorProxies.now(LocatorProxies.java:125)
        at org.fluentlenium.core.domain.FluentWebElement.now(FluentWebElement.java:136)
        at org.fluentlenium.adapter.testng.integration.AutomaticOnFailTest.test(AutomaticOnFailTest.java:26)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
        at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
        at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
        at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
        at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
        at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Error while instrumenting class com/gargoylesoftware/css/parser/javacc/CSS3ParserTokenManager.
        at org.jacoco.agent.rt.internal_b0d6a23.core.instr.Instrumenter.instrumentError(Instrumenter.java:152)
        at org.jacoco.agent.rt.internal_b0d6a23.core.instr.Instrumenter.instrument(Instrumenter.java:103)
        at org.jacoco.agent.rt.internal_b0d6a23.CoverageTransformer.transform(CoverageTransformer.java:93)
        ... 45 more
Caused by: java.lang.RuntimeException: Method code too large!
        at org.jacoco.agent.rt.internal_b0d6a23.asm.MethodWriter.getSize(MethodWriter.java:2036)
        at org.jacoco.agent.rt.internal_b0d6a23.asm.ClassWriter.toByteArray(ClassWriter.java:827)
        at org.jacoco.agent.rt.internal_b0d6a23.core.instr.Instrumenter.instrument(Instrumenter.java:84)
        at org.jacoco.agent.rt.internal_b0d6a23.core.instr.Instrumenter.instrument(Instrumenter.java:101)
        ... 46 more`

It would be nice to investigate this and remove the issue.
I think it may be related to operating system (Windows) because on other os (Linux) I've not seen this.

**Comment by filipcynarski** [comment]
I'm seeing that on OS X as well.

**Comment by filipcynarski** [comment]
I think we are facing it due to jacoco agent issues, it was described here, I'll try to fix it.

**Comment by filipcynarski** [comment]
Exception is handled, will be pushed to the code base today.
