### ISSUE TITLE
Selenium 4 support

### ISSUE THREAD

**Issue by slawekradzyminski** [FluentLenium/FluentLenium#828]
`4.0.0-alpha-1` has been published. We may start to work on updating Selenium dependency

**Comment by slawekradzyminski** [comment]
This commit is problematic as it breaks our CapabilitiesFactory ;)
https://github.com/SeleniumHQ/selenium/commit/c982edfbd3eed3ffb9666c4f3e9df7c004834c22#diff-63c65aee22b3993563276bfa4f82a733

**Comment by slawekradzyminski** [comment]
Two issues:
1. HtmlUnitDriver() throws NoClassDefFoundError

`java.lang.NoClassDefFoundError: org/openqa/selenium/interactions/internal/Locatable

	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:802)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:700)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:623)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at org.openqa.selenium.htmlunit.HtmlUnitDriver.toWebElement(HtmlUnitDriver.java:1212)
	at org.openqa.selenium.htmlunit.HtmlUnitDriver.findElementsByCssSelector(HtmlUnitDriver.java:1325)
	at org.openqa.selenium.By$ByCssSelector.findElements(By.java:441)
	at org.openqa.selenium.htmlunit.HtmlUnitDriver.findElements(HtmlUnitDriver.java:2037)
	at org.openqa.selenium.htmlunit.HtmlUnitDriver.findElements(HtmlUnitDriver.java:804)
	at org.fluentlenium.core.search.Search$2.findElements(Search.java:103)
	at org.fluentlenium.core.proxy.ListHandler.getLocatorResultImpl(ListHandler.java:78)
	at org.fluentlenium.core.proxy.ListHandler.getLocatorResultImpl(ListHandler.java:18)
`

2. I moved removed methods from DesiredCapabilites to PredefinedDesiredCapabilities.class. We need to decide what to do with it.

**Comment by lafkob** [comment]
Recently upgraded a project to java 11 and upgraded all our test dependencies. I am seeing this pop up in our Fluentlenium tests and wondering if someone can throw me a lifeline :smiley: 

java.lang.NoClassDefFoundError: org/openqa/selenium/interactions/Coordinates
	at org.openqa.selenium.htmlunit.HtmlUnitDriver.toWebElement(HtmlUnitDriver.java:1207)
	at org.openqa.selenium.htmlunit.HtmlUnitDriver.findElementsByCssSelector(HtmlUnitDriver.java:1320)
	at org.openqa.selenium.By$ByCssSelector.findElements(By.java:441)
	at org.openqa.selenium.htmlunit.HtmlUnitDriver.findElements(HtmlUnitDriver.java:2027)
	at org.openqa.selenium.htmlunit.HtmlUnitDriver.findElements(HtmlUnitDriver.java:799)
	at org.fluentlenium.core.search.Search$2.findElements(Search.java:103)
	at org.fluentlenium.core.proxy.ListHandler.getLocatorResultImpl(ListHandler.java:76)
	at org.fluentlenium.core.proxy.ListHandler.getLocatorResultImpl(ListHandler.java:16)
	at org.fluentlenium.core.proxy.AbstractLocatorHandler.getLocatorResult(AbstractLocatorHandler.java:139)
	at org.fluentlenium.core.proxy.AbstractLocatorHandler.invoke(AbstractLocatorHandler.java:254)
	at org.fluentlenium.core.proxy.ListHandler.invoke(ListHandler.java:98)
	at com.sun.proxy.$Proxy140.iterator(Unknown Source)
	at org.fluentlenium.core.components.LazyComponentList.transformList(LazyComponentList.java:63)
	at org.fluentlenium.core.components.LazyComponentList.getList(LazyComponentList.java:46)
	at org.fluentlenium.core.domain.ListImpl.size(ListImpl.java:53)
	at org.fluentlenium.core.domain.ListImpl.size(ListImpl.java:53)
	at org.fluentlenium.core.domain.FluentListImpl.validateListIsNotEmpty(FluentListImpl.java:504)
	at org.fluentlenium.core.domain.FluentListImpl.write(FluentListImpl.java:238)
	at org.fluentlenium.core.action.Fill.with(Fill.java:38)

**Comment by Jose-Luis-Nunez** [comment]
Hey dear FluentLenium team I saw a PR for Selenium 4 https://github.com/FluentLenium/FluentLenium/pull/1356
 will it be released soon?

**Comment by abendt** [comment]
https://github.com/FluentLenium/FluentLenium/releases/tag/v5.0.1
