### ISSUE TITLE
Assertions fail in an incorrect way due to AbstractAssert#failWithMessage

### ISSUE THREAD

**Issue by picimako** [FluentLenium/FluentLenium#857]
I've just wrote a unit test in `FluentWebElementTest` for the negative case of `hasTextMatching`:

```java
@Test
public void shouldFailWhenHasTextNotMatching() {
    when(element.text()).thenReturn("There is a 5% increase");
    assertThatThrownBy(() -> elementAssert.hasTextMatching("There is a \\d%")).isInstanceOf(AssertionError.class);
}
```
which instead of failing with the expected *"The element does not match the regex:...* message, it fails during String.format() in `org.assertj.core.api.AbstractAssert#failWithMessage()` with the following error:
```
java.util.UnknownFormatConversionException: Conversion = '.'
	at java.base/java.util.Formatter.checkText(Formatter.java:2732)
	at java.base/java.util.Formatter.parse(Formatter.java:2708)
	at java.base/java.util.Formatter.format(Formatter.java:2655)
	at java.base/java.util.Formatter.format(Formatter.java:2609)
	at java.base/java.lang.String.format(String.java:2897)
	at org.assertj.core.api.AbstractAssert.failWithMessage(AbstractAssert.java:133)
	at org.fluentlenium.assertj.custom.FluentWebElementAssert.hasTextMatching(FluentWebElementAssert.java:126)
	at org.fluentlenium.assertj.custom.FluentWebElementTest.lambda$shouldFailWhenHasTextNotMatching$4(FluentWebElementTest.java:294)
	at org.assertj.core.api.ThrowableAssert.catchThrowable(ThrowableAssert.java:62)
	at org.assertj.core.api.AssertionsForClassTypes.catchThrowable(AssertionsForClassTypes.java:739)
	at org.assertj.core.api.Assertions.catchThrowable(Assertions.java:1163)
	at org.assertj.core.api.Assertions.assertThatThrownBy(Assertions.java:1032)
	at org.fluentlenium.assertj.AssertionTestSupport.assertThatAssertionErrorIsThrownBy(AssertionTestSupport.java:24)
	at org.fluentlenium.assertj.custom.FluentWebElementTest.shouldFailWhenHasTextNotMatching(FluentWebElementTest.java:294)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
```
This is a general issue with any assertion using `failWithMessage()`, and so far it seems to me that it may be related to the placeholder identifiers used by String,format, like the `%` character, but not only the % character.

In the scope of this issue it needs to be checked:
- what the exact issue is
- whether there is an open issue on AssertJ's side for this
- whether/how this can be worked around in FluentLenium

**Comment by picimako** [comment]
There are two probably related issues for AssertJ:
- https://github.com/joel-costigliola/assertj-core/issues/1441
- https://github.com/joel-costigliola/assertj-core/issues/1500

They are probably going to be released in assertj 3.13.0, so when it happens it should revisited with that version.

**Comment by picimako** [comment]
AssertJ 3.13.2 has been released so this issue may be revisited.

**Comment by picimako** [comment]
Closing this ticket as it is clearly an AssertJ issue and not related to FluentLenium logic.
