### ISSUE TITLE
Spock Example does not work when adding the firefox selenium driver to the pom.xml

### ISSUE THREAD

**Issue by argonauta** [FluentLenium/FluentLenium#995]
**I tried to use Firefox for the test and added this dependency to the pom**

` <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-firefox-driver</artifactId>
            <version>${selenium.version}</version>
    </dependency>
`

**After that the org.fluentlenium.example.spock.DuckDuckGoSpec throws this Exception**

`org.openqa.selenium.WebDriverException: Browser failed to start, test [ Title of duck duck go(org.fluentlenium.example.spock.DuckDuckGoSpec) ] execution interrupted.
Caused by: [ The path to the driver executable must be set by the webdriver.gecko.driver system property; for more information, see https://github.com/mozilla/geckodriver. The latest version can be downloaded from https://github.com/mozilla/geckodriver/releases]
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'xxx.local', ip: 'xxx.xxx.xxx.xxx', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.2', java.version: '11.0.3'
Driver info: driver.version: unknown

	at org.fluentlenium.adapter.FluentTestRunnerAdapter.starting(FluentTestRunnerAdapter.java:211)
	at org.fluentlenium.adapter.spock.FluentSpecificationAdapter.specStarting(FluentSpecificationAdapter.groovy:13)
	at org.fluentlenium.adapter.spock.FluentSpecification.specStarting(FluentSpecification.groovy:20)
	at org.fluentlenium.adapter.spock.FluentSpecification$1.starting(FluentSpecification.groovy:45)
	at org.fluentlenium.adapter.junit.FluentTestRule$1.evaluate(FluentTestRule.java:44)
	at org.spockframework.runtime.extension.builtin.TestRuleInterceptor.intercept(TestRuleInterceptor.java:39)
	at org.spockframework.runtime.extension.MethodInvocation.proceed(MethodInvocation.java:97)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.util.concurrent.ExecutionException: org.fluentlenium.configuration.ConfigurationException: Can't create new WebDriver instance
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at org.fluentlenium.adapter.FluentTestRunnerAdapter.getSharedWebDriver(FluentTestRunnerAdapter.java:271)
	at org.fluentlenium.adapter.FluentTestRunnerAdapter.getSharedWebDriver(FluentTestRunnerAdapter.java:247)
	at org.fluentlenium.adapter.FluentTestRunnerAdapter.starting(FluentTestRunnerAdapter.java:204)
	... 11 more
Caused by: org.fluentlenium.configuration.ConfigurationException: Can't create new WebDriver instance
	at org.fluentlenium.configuration.ReflectiveWebDriverFactory.newWebDriver(ReflectiveWebDriverFactory.java:104)
	at org.fluentlenium.configuration.WebDriversRegistryImpl.newWebDriver(WebDriversRegistryImpl.java:48)
	at org.fluentlenium.configuration.WebDrivers.newWebDriver(WebDrivers.java:38)
	at org.fluentlenium.adapter.FluentAdapter.newWebDriver(FluentAdapter.java:135)
	at org.fluentlenium.adapter.sharedwebdriver.SharedWebdriverSingletonImpl.createDriver(SharedWebdriverSingletonImpl.java:63)
	at org.fluentlenium.adapter.sharedwebdriver.SharedWebdriverSingletonImpl.createAndRegisterNewDriver(SharedWebdriverSingletonImpl.java:57)
	at org.fluentlenium.adapter.sharedwebdriver.SharedWebdriverSingletonImpl.lambda$getOrCreateDriver$0(SharedWebdriverSingletonImpl.java:52)
	at java.base/java.util.Optional.orElseGet(Optional.java:369)
	at org.fluentlenium.adapter.sharedwebdriver.SharedWebdriverSingletonImpl.getOrCreateDriver(SharedWebdriverSingletonImpl.java:52)
	at org.fluentlenium.adapter.sharedwebdriver.SharedWebDriverContainer.getOrCreateDriver(SharedWebDriverContainer.java:37)
	at org.fluentlenium.adapter.FluentTestRunnerAdapter.lambda$createDriver$1(FluentTestRunnerAdapter.java:299)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.reflect.InvocationTargetException
	at org.fluentlenium.utils.ReflectionUtils.newInstance(ReflectionUtils.java:234)
	at org.fluentlenium.configuration.ReflectiveWebDriverFactory.newInstance(ReflectiveWebDriverFactory.java:127)
	at org.fluentlenium.configuration.ReflectiveWebDriverFactory.newWebDriver(ReflectiveWebDriverFactory.java:102)
	... 14 more
Caused by: java.lang.IllegalStateException: The path to the driver executable must be set by the webdriver.gecko.driver system property; for more information, see https://github.com/mozilla/geckodriver. The latest version can be downloaded from https://github.com/mozilla/geckodriver/releases
	at com.google.common.base.Preconditions.checkState(Preconditions.java:847)
	at org.openqa.selenium.remote.service.DriverService.findExecutable(DriverService.java:134)
	at org.openqa.selenium.firefox.GeckoDriverService.access$100(GeckoDriverService.java:44)
	at org.openqa.selenium.firefox.GeckoDriverService$Builder.findDefaultExecutable(GeckoDriverService.java:167)
	at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:355)
	at org.openqa.selenium.firefox.FirefoxDriver.toExecutor(FirefoxDriver.java:190)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:147)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:125)
	... 17 more
`

**It looks like that selecting the driver with overriding the getWebDriver method of FluentSpecification is not working.
I tried also in the DuckDuckGoSpec to override the getCapabilities method to use the chrome headless browser, after removing the firefox driver from the pom.xml. And it was not using the headless chrome.**

` @Override
    String getWebDriver() {
        return new ChromeDriver()
    }

    @Override
    Capabilities getCapabilities() {
        ChromeOptions options = new ChromeOptions()
        options.addArguments("--headless")
        options.addArguments("--disable-gpu")
    }

    def "Title of duck duck go"() {
        given:
        goTo("https://duckduckgo.com")

        when:
        el("input.js-search-input.search__input--adv").fill().with(SEARCH_TEXT)
        el("#search_form_homepage_top").submit()
        await().untilWindow(SEARCH_TEXT)

        then:
        window().title().contains(SEARCH_TEXT)
    }`
**Btw the example is broken because the DuckDuckGo Page did change. I fixed the css selectors.**

**Comment by slawekradzyminski** [comment]
Yes, it's broken unfortunately. Spock module was added by community and we tend to struggle with it. Let's see what can be done here.

**Comment by slawekradzyminski** [comment]
@argonauta ok nvm, got it working after a lot of tinkering ;)

**Comment by slawekradzyminski** [comment]
It's done, seems like everything is working
